<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ko" xml:lang="ko"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="템플스테이 수요 예측 논문을 공개 통계로 재현·검증하며 Bass 확산 모형의 개념, 추정, 예측 검증, 정책 시나리오까지 단계별로 정리했습니다.">

<title>Bass 확산 모형 입문 가이드: 템플스테이 수요 예측 사례 – 통계분석 실습 노트</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-234273d1456647dabc34a594ac50e507.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-0348920b7671f696dc9078d39bff215e.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-234273d1456647dabc34a594ac50e507.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-194a334aaccc957a8006bea1e7e7ef2a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-93ecdb9deeaa6e6d8da72ceae2faebe8.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-194a334aaccc957a8006bea1e7e7ef2a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "일치 없음",
    "search-matching-documents-text": "일치된 문서",
    "search-copy-link-title": "검색 링크 복사",
    "search-hide-matches-text": "추가 검색 결과 숨기기",
    "search-more-match-text": "추가 검색결과",
    "search-more-matches-text": "추가 검색결과",
    "search-clear-button-title": "제거",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "취소",
    "search-submit-button-title": "검색",
    "search-label": "검색"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css">


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">통계분석 실습 노트</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="검색"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="탐색 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">글 목록</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">소개</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/JinwooChung/JinwooChung.github.io"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="다크 모드 전환"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">목차</h2>
   
  <ul>
  <li><a href="#한-페이지-요약" id="toc-한-페이지-요약" class="nav-link active" data-scroll-target="#한-페이지-요약">1. 한 페이지 요약</a>
  <ul class="collapse">
  <li><a href="#무엇을-했나" id="toc-무엇을-했나" class="nav-link" data-scroll-target="#무엇을-했나">1.1 무엇을 했나</a></li>
  <li><a href="#무엇을-알게-됐나" id="toc-무엇을-알게-됐나" class="nav-link" data-scroll-target="#무엇을-알게-됐나">1.2 무엇을 알게 됐나</a></li>
  <li><a href="#가장-중요한-교훈" id="toc-가장-중요한-교훈" class="nav-link" data-scroll-target="#가장-중요한-교훈">1.3 가장 중요한 교훈</a></li>
  </ul></li>
  <li><a href="#bass-확산-모형이란-무엇인가" id="toc-bass-확산-모형이란-무엇인가" class="nav-link" data-scroll-target="#bass-확산-모형이란-무엇인가">2. Bass 확산 모형이란 무엇인가</a>
  <ul class="collapse">
  <li><a href="#출발점-새로운-것은-어떻게-퍼지는가" id="toc-출발점-새로운-것은-어떻게-퍼지는가" class="nav-link" data-scroll-target="#출발점-새로운-것은-어떻게-퍼지는가">2.1 출발점: 새로운 것은 어떻게 퍼지는가</a></li>
  <li><a href="#bass-모형-확산을-두-가지-힘으로-설명" id="toc-bass-모형-확산을-두-가지-힘으로-설명" class="nav-link" data-scroll-target="#bass-모형-확산을-두-가지-힘으로-설명">2.2 Bass 모형: 확산을 두 가지 힘으로 설명</a></li>
  <li><a href="#모형이-알려-주는-것" id="toc-모형이-알려-주는-것" class="nav-link" data-scroll-target="#모형이-알려-주는-것">2.3 모형이 알려 주는 것</a></li>
  <li><a href="#선택-수식으로-보기" id="toc-선택-수식으로-보기" class="nav-link" data-scroll-target="#선택-수식으로-보기">2.4 (선택) 수식으로 보기</a></li>
  </ul></li>
  <li><a href="#언제-잘-맞고-언제-조심해야-하는가" id="toc-언제-잘-맞고-언제-조심해야-하는가" class="nav-link" data-scroll-target="#언제-잘-맞고-언제-조심해야-하는가">3. 언제 잘 맞고, 언제 조심해야 하는가</a>
  <ul class="collapse">
  <li><a href="#기본-bass-모형의-네-가지-가정" id="toc-기본-bass-모형의-네-가지-가정" class="nav-link" data-scroll-target="#기본-bass-모형의-네-가지-가정">3.1 기본 Bass 모형의 네 가지 가정</a></li>
  <li><a href="#잘-맞는-경우" id="toc-잘-맞는-경우" class="nav-link" data-scroll-target="#잘-맞는-경우">3.2 잘 맞는 경우</a></li>
  <li><a href="#조심해야-하는-경우" id="toc-조심해야-하는-경우" class="nav-link" data-scroll-target="#조심해야-하는-경우">3.3 조심해야 하는 경우</a></li>
  <li><a href="#데이터가-갖춰야-할-최소-요건" id="toc-데이터가-갖춰야-할-최소-요건" class="nav-link" data-scroll-target="#데이터가-갖춰야-할-최소-요건">3.4 데이터가 갖춰야 할 최소 요건</a></li>
  </ul></li>
  <li><a href="#알아두면-좋은-용어" id="toc-알아두면-좋은-용어" class="nav-link" data-scroll-target="#알아두면-좋은-용어">4. 알아두면 좋은 용어</a>
  <ul class="collapse">
  <li><a href="#자료에-관한-용어" id="toc-자료에-관한-용어" class="nav-link" data-scroll-target="#자료에-관한-용어">4.1 자료에 관한 용어</a></li>
  <li><a href="#추정-방법에-관한-용어" id="toc-추정-방법에-관한-용어" class="nav-link" data-scroll-target="#추정-방법에-관한-용어">4.2 추정 방법에 관한 용어</a></li>
  <li><a href="#모형을-평가하는-용어" id="toc-모형을-평가하는-용어" class="nav-link" data-scroll-target="#모형을-평가하는-용어">4.3 모형을 평가하는 용어</a></li>
  <li><a href="#예측을-검증하는-용어" id="toc-예측을-검증하는-용어" class="nav-link" data-scroll-target="#예측을-검증하는-용어">4.4 예측을 검증하는 용어</a></li>
  <li><a href="#모형-확장에-관한-용어" id="toc-모형-확장에-관한-용어" class="nav-link" data-scroll-target="#모형-확장에-관한-용어">4.5 모형 확장에 관한 용어</a></li>
  </ul></li>
  <li><a href="#실습-템플스테이-자료로-단계별-분석하기" id="toc-실습-템플스테이-자료로-단계별-분석하기" class="nav-link" data-scroll-target="#실습-템플스테이-자료로-단계별-분석하기">5. 실습: 템플스테이 자료로 단계별 분석하기</a>
  <ul class="collapse">
  <li><a href="#출발점-논문과-데이터" id="toc-출발점-논문과-데이터" class="nav-link" data-scroll-target="#출발점-논문과-데이터">5.0 출발점: 논문과 데이터</a></li>
  <li><a href="#전체-흐름" id="toc-전체-흐름" class="nav-link" data-scroll-target="#전체-흐름">5.1 전체 흐름</a></li>
  <li><a href="#단계-자료-살펴보기" id="toc-단계-자료-살펴보기" class="nav-link" data-scroll-target="#단계-자료-살펴보기">5.2 1단계: 자료 살펴보기</a></li>
  <li><a href="#단계-세-가지-방법으로-기본-추정" id="toc-단계-세-가지-방법으로-기본-추정" class="nav-link" data-scroll-target="#단계-세-가지-방법으로-기본-추정">5.3 2단계: 세 가지 방법으로 기본 추정</a></li>
  <li><a href="#단계-분석-설정을-바꿔-보기" id="toc-단계-분석-설정을-바꿔-보기" class="nav-link" data-scroll-target="#단계-분석-설정을-바꿔-보기">5.4 3단계: 분석 설정을 바꿔 보기</a></li>
  <li><a href="#단계-예측-시험과-논문-재현" id="toc-단계-예측-시험과-논문-재현" class="nav-link" data-scroll-target="#단계-예측-시험과-논문-재현">5.5 4단계: 예측 시험과 논문 재현</a></li>
  <li><a href="#단계-자료가-쌓일수록-추정이-안정되는가-rolling-origin" id="toc-단계-자료가-쌓일수록-추정이-안정되는가-rolling-origin" class="nav-link" data-scroll-target="#단계-자료가-쌓일수록-추정이-안정되는가-rolling-origin">5.6 5단계: 자료가 쌓일수록 추정이 안정되는가 (Rolling origin)</a></li>
  <li><a href="#단계-공급을-반영한-모형과-정책-시나리오" id="toc-단계-공급을-반영한-모형과-정책-시나리오" class="nav-link" data-scroll-target="#단계-공급을-반영한-모형과-정책-시나리오">5.7 6단계: 공급을 반영한 모형과 정책 시나리오</a></li>
  </ul></li>
  <li><a href="#종합-결론과-교훈" id="toc-종합-결론과-교훈" class="nav-link" data-scroll-target="#종합-결론과-교훈">6. 종합 결론과 교훈</a>
  <ul class="collapse">
  <li><a href="#분석-전체를-한-문단으로" id="toc-분석-전체를-한-문단으로" class="nav-link" data-scroll-target="#분석-전체를-한-문단으로">6.1 분석 전체를 한 문단으로</a></li>
  <li><a href="#기본-bass-모형의-가정과-템플스테이의-현실" id="toc-기본-bass-모형의-가정과-템플스테이의-현실" class="nav-link" data-scroll-target="#기본-bass-모형의-가정과-템플스테이의-현실">6.2 기본 Bass 모형의 가정과 템플스테이의 현실</a></li>
  <li><a href="#이-실습에서-얻는-교훈" id="toc-이-실습에서-얻는-교훈" class="nav-link" data-scroll-target="#이-실습에서-얻는-교훈">6.3 이 실습에서 얻는 교훈</a></li>
  </ul></li>
  <li><a href="#정책에-주는-시사점" id="toc-정책에-주는-시사점" class="nav-link" data-scroll-target="#정책에-주는-시사점">7. 정책에 주는 시사점</a></li>
  <li><a href="#내-자료에-적용할-때-체크리스트와-함정" id="toc-내-자료에-적용할-때-체크리스트와-함정" class="nav-link" data-scroll-target="#내-자료에-적용할-때-체크리스트와-함정">8. 내 자료에 적용할 때: 체크리스트와 함정</a>
  <ul class="collapse">
  <li><a href="#단계별-체크리스트" id="toc-단계별-체크리스트" class="nav-link" data-scroll-target="#단계별-체크리스트">8.1 단계별 체크리스트</a></li>
  <li><a href="#자주-빠지는-해석의-함정" id="toc-자주-빠지는-해석의-함정" class="nav-link" data-scroll-target="#자주-빠지는-해석의-함정">8.2 자주 빠지는 해석의 함정</a></li>
  </ul></li>
  <li><a href="#결과를-보고하는-법" id="toc-결과를-보고하는-법" class="nav-link" data-scroll-target="#결과를-보고하는-법">9. 결과를 보고하는 법</a>
  <ul class="collapse">
  <li><a href="#표현-원칙" id="toc-표현-원칙" class="nav-link" data-scroll-target="#표현-원칙">9.1 표현 원칙</a></li>
  <li><a href="#보고서에-담을-내용" id="toc-보고서에-담을-내용" class="nav-link" data-scroll-target="#보고서에-담을-내용">9.2 보고서에 담을 내용</a></li>
  </ul></li>
  <li><a href="#파일-구성과-실행-방법" id="toc-파일-구성과-실행-방법" class="nav-link" data-scroll-target="#파일-구성과-실행-방법">10. 파일 구성과 실행 방법</a>
  <ul class="collapse">
  <li><a href="#폴더-구성" id="toc-폴더-구성" class="nav-link" data-scroll-target="#폴더-구성">10.1 폴더 구성</a></li>
  <li><a href="#실행-방법" id="toc-실행-방법" class="nav-link" data-scroll-target="#실행-방법">10.2 실행 방법</a></li>
  <li><a href="#다른-자료에-적용하려면" id="toc-다른-자료에-적용하려면" class="nav-link" data-scroll-target="#다른-자료에-적용하려면">10.3 다른 자료에 적용하려면</a></li>
  <li><a href="#주요-함수-bass_functions.r" id="toc-주요-함수-bass_functions.r" class="nav-link" data-scroll-target="#주요-함수-bass_functions.r">10.4 주요 함수 (<code>bass_functions.R</code>)</a></li>
  </ul></li>
  <li><a href="#자주-묻는-질문" id="toc-자주-묻는-질문" class="nav-link" data-scroll-target="#자주-묻는-질문">11. 자주 묻는 질문</a></li>
  <li><a href="#참고문헌" id="toc-참고문헌" class="nav-link" data-scroll-target="#참고문헌">12. 참고문헌</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Bass 확산 모형 입문 가이드: 템플스테이 수요 예측 사례</h1>
  <div class="quarto-categories">
    <div class="quarto-category">수요 예측</div>
    <div class="quarto-category">확산 모형</div>
    <div class="quarto-category">R</div>
  </div>
  </div>

<div>
  <div class="description">
    템플스테이 수요 예측 논문을 공개 통계로 재현·검증하며 Bass 확산 모형의 개념, 추정, 예측 검증, 정책 시나리오까지 단계별로 정리했습니다.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">공개</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2026년 9월 28일</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>코드와 데이터:</strong> <a href="../../posts/bass-diffusion/code.html">스크립트 보기</a> · <a href="files/bass-diffusion.zip">전체 내려받기 (zip)</a></p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>이 문서는 무엇인가요?</strong> 템플스테이 수요를 Bass 확산 모형으로 예측한 논문 한 편을 출발점으로, 공개 통계를 이용해 <strong>분석 전 과정을 직접 재현하고 검증해 본 기록</strong>입니다. 동료들과 공유하고, 비슷한 자료를 분석할 때 참고서로 쓰기 위해 정리했습니다.</p>
<p><strong>대상:</strong> 평균, 회귀분석, 그래프 읽기 정도는 익숙하지만, 수요 예측 모형은 처음이거나 익숙하지 않은 분</p>
<p><strong>읽는 순서:</strong> 처음이라면 <strong>1장(요약) → 2장(모형 개념) → 5장(단계별 실습)</strong> 순서를 권합니다. 모르는 용어가 나오면 <strong>4장(용어 풀이)</strong>으로 돌아가 보세요. 수식은 몰라도 읽을 수 있도록, 수식은 “선택” 표시가 된 곳에만 모아 두었습니다.</p>
<p><strong>함께 보는 파일:</strong> <a href="../../posts/bass-diffusion/code.html">코드와 데이터</a> 페이지의 R 스크립트 6개와 예시 자료 (10장 참고)</p>
</blockquote>
<hr>
<section id="한-페이지-요약" class="level2">
<h2 class="anchored" data-anchor-id="한-페이지-요약">1. 한 페이지 요약</h2>
<section id="무엇을-했나" class="level3">
<h3 class="anchored" data-anchor-id="무엇을-했나">1.1 무엇을 했나</h3>
<p>2024년에 발표된 한 논문은 템플스테이 참가자 수에 Bass 확산 모형을 적용해 <strong>“2023년에 이미 잠재 수요의 77%가 참가했고, 앞으로 수요가 줄어든다”</strong>고 예측했습니다. 이 분석을 같은 방법으로 재현하고, 이후 실제 자료(2024~2025년)와 비교하고, 다른 방법으로도 분석해 봤습니다.</p>
</section>
<section id="무엇을-알게-됐나" class="level3">
<h3 class="anchored" data-anchor-id="무엇을-알게-됐나">1.2 무엇을 알게 됐나</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>질문</th>
<th>쉽게 말한 답</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>논문의 예측은 맞았나?</td>
<td><strong>틀렸습니다.</strong> 논문은 감소를 예측했지만, 실제 참가자(순인원)는 2024년 +15.9%, 2025년 +5.1%로 <strong>역대 최다</strong>를 기록했습니다.</td>
</tr>
<tr class="even">
<td>논문은 어떻게 계산했나?</td>
<td>가장 단순한 추정 방법(OLS)을 썼고, 저희가 같은 방법으로 계산하자 논문의 숫자가 거의 그대로 나왔습니다.</td>
</tr>
<tr class="odd">
<td>기본 Bass 모형이 이 자료에 맞나?</td>
<td><strong>잘 맞지 않습니다.</strong> 계산 방법만 바꿔도 “앞으로 참가할 총인원”이 524만~858만 명으로 크게 달라졌고, 예측 시험에서는 “작년 값 그대로”라는 가장 단순한 예측에도 졌습니다.</td>
</tr>
<tr class="even">
<td>왜 안 맞았나?</td>
<td>기본 모형은 “한 사람은 한 번만 참가하고, 시장 크기는 정해져 있다”고 가정합니다. 그런데 템플스테이는 <strong>다시 오는 사람이 있고, 운영 사찰 수(공급)가 계속 늘어난</strong> 시장입니다.</td>
</tr>
<tr class="odd">
<td>어떻게 고쳤나?</td>
<td>“시장 크기가 사찰 수에 비례해 커진다”고 모형을 바꾸자 오차가 <strong>절반</strong>으로 줄었습니다.</td>
</tr>
<tr class="even">
<td>정책적으로는?</td>
<td>사찰 수를 그대로 두면 2030년대에 연간 참가자가 줄고, 매년 6곳씩 늘리면 2035년 연간 약 40만 명까지 늘어납니다. 단, <strong>새 사찰의 질(만족도)이 떨어지면 효과가 크게 줄어듭니다.</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="가장-중요한-교훈" class="level3">
<h3 class="anchored" data-anchor-id="가장-중요한-교훈">1.3 가장 중요한 교훈</h3>
<blockquote class="blockquote">
<p><strong>모형의 결론은 모형의 가정에서 나옵니다.</strong> 같은 자료라도 “시장 크기가 고정되어 있다”고 가정하면 “이미 포화 중”이라는 결론이 나오고, “공급이 시장을 키운다”고 가정하면 “수요는 공급 정책에 달려 있다”는 결론이 나옵니다.</p>
</blockquote>
<hr>
</section>
</section>
<section id="bass-확산-모형이란-무엇인가" class="level2">
<h2 class="anchored" data-anchor-id="bass-확산-모형이란-무엇인가">2. Bass 확산 모형이란 무엇인가</h2>
<section id="출발점-새로운-것은-어떻게-퍼지는가" class="level3">
<h3 class="anchored" data-anchor-id="출발점-새로운-것은-어떻게-퍼지는가">2.1 출발점: 새로운 것은 어떻게 퍼지는가</h3>
<p>스마트폰이 처음 나왔을 때를 떠올려 보세요.</p>
<ul>
<li>처음에는 <strong>새것을 좋아하는 소수</strong>만 삽니다.</li>
<li>주변에 쓰는 사람이 늘면 <strong>“나도 써 볼까”</strong> 하는 사람이 빠르게 늘어납니다.</li>
<li>대부분이 갖게 되면 새로 사는 사람은 <strong>점점 줄어듭니다.</strong></li>
</ul>
<p>그래서 해마다 <strong>새로 산 사람 수</strong>를 그래프로 그리면 <strong>종 모양</strong>(늘다가 정점을 찍고 줄어듦)이 되고, <strong>지금까지 산 사람의 누적</strong>을 그리면 <strong>S자 곡선</strong>이 됩니다. 사회학자 로저스(Rogers, 1962)가 정리한 <strong>혁신 확산 이론</strong>입니다.</p>
<pre><code> 해마다 새로 채택한 사람 (종 모양)        누적 채택자 (S자)

        ▁▃▆█▆▃▁                                  ▁▁▁▁  ← 천장 (m)
      ▁▃       ▃▁                             ▃▆
    ▁▃           ▃▁                         ▃
  ▁▃               ▃▁                    ▁▃
 ─────────────────────▶ 시간         ▁▁▁▃ ──────────▶ 시간
          ↑ 정점</code></pre>
<p>로저스는 받아들이는 시점에 따라 사람들을 다섯 부류로 나눴습니다.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>부류</th>
<th>비율</th>
<th>특징</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>혁신층</td>
<td>2.5%</td>
<td>새로운 것 자체를 즐기고 위험을 감수</td>
</tr>
<tr class="even">
<td>초기 수용층</td>
<td>13.5%</td>
<td>여론 주도층, 남보다 먼저 받아들임</td>
</tr>
<tr class="odd">
<td>초기 다수층</td>
<td>34%</td>
<td>신중하지만 평균보다 먼저</td>
</tr>
<tr class="even">
<td>후기 다수층</td>
<td>34%</td>
<td>대다수가 쓴 뒤에 받아들임</td>
</tr>
<tr class="odd">
<td>지체층</td>
<td>16%</td>
<td>가장 늦게, 또는 끝까지 받아들이지 않음</td>
</tr>
</tbody>
</table>
<p>신규 채택이 가장 많은 <strong>정점</strong>은 대략 <strong>잠재 고객의 절반 가까이가 채택했을 때</strong> 나타납니다.</p>
</section>
<section id="bass-모형-확산을-두-가지-힘으로-설명" class="level3">
<h3 class="anchored" data-anchor-id="bass-모형-확산을-두-가지-힘으로-설명">2.2 Bass 모형: 확산을 두 가지 힘으로 설명</h3>
<p>바스(Bass, 1969)는 이 과정을 숫자로 계산할 수 있게 만들었습니다. 사람들이 새것을 받아들이는 이유를 <strong>두 가지 힘</strong>으로 단순화합니다.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>힘</th>
<th>기호</th>
<th>뜻</th>
<th>비유</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>외부 영향 (혁신 효과)</strong></td>
<td><strong>p</strong></td>
<td>남과 상관없이 광고·언론을 보고 스스로 채택</td>
<td>신문에서 새 식당 기사를 보고 찾아감</td>
</tr>
<tr class="even">
<td><strong>내부 영향 (모방 효과)</strong></td>
<td><strong>q</strong></td>
<td>이미 채택한 사람의 입소문을 듣고 채택</td>
<td>친구가 가 봤는데 좋더라고 해서 찾아감</td>
</tr>
</tbody>
</table>
<p>그리고 여기에 하나가 더 필요합니다.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>기호</th>
<th>뜻</th>
<th>비유</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>m (잠재시장)</strong></td>
<td>결국 채택하게 될 사람의 총수. 누적 S자 곡선의 <strong>천장</strong></td>
<td>그 식당에 언젠가 한 번이라도 갈 사람의 총수</td>
</tr>
</tbody>
</table>
<p><strong>작동 방식을 말로 풀면:</strong></p>
<ul>
<li>초기에는 채택한 사람이 거의 없어서 입소문(q)이 약합니다. 주로 광고(p)의 힘으로 조금씩 늘어납니다.</li>
<li>채택자가 늘수록 입소문의 힘이 커져서 증가가 빨라집니다.</li>
<li>아직 채택하지 않은 사람(m − 누적 채택자)이 줄어들면서 증가가 느려지고, 결국 천장 m에 다가갑니다.</li>
</ul>
<p><strong>p와 q의 일반적인 크기:</strong> p는 보통 0.01~0.03, q는 0.3~0.5 범위입니다. 여러 제품을 모아 분석한 연구(Sultan, Farley &amp; Lehmann, 1990)에 따르면 평균적으로 <strong>p ≈ 0.03, q ≈ 0.38</strong> 정도이고, 새 제품의 자료가 부족할 때 이런 값을 빌려 쓰기도 합니다. 대개 <strong>q가 p보다 훨씬 커서</strong>, 확산은 광고보다 입소문으로 퍼진다고 볼 수 있습니다.</p>
</section>
<section id="모형이-알려-주는-것" class="level3">
<h3 class="anchored" data-anchor-id="모형이-알려-주는-것">2.3 모형이 알려 주는 것</h3>
<p>p, q, m 세 숫자를 추정하면 다음을 계산할 수 있습니다.</p>
<ul>
<li><strong>정점 시점:</strong> 연간 신규 채택이 가장 많은 해는 언제인가</li>
<li><strong>정점 규모:</strong> 그해 몇 명이 새로 채택하는가</li>
<li><strong>도달률:</strong> 지금까지 잠재시장의 몇 %가 채택했는가</li>
<li><strong>미래 예측:</strong> 앞으로 해마다 몇 명이 새로 채택하는가</li>
</ul>
</section>
<section id="선택-수식으로-보기" class="level3">
<h3 class="anchored" data-anchor-id="선택-수식으로-보기">2.4 (선택) 수식으로 보기</h3>
<p>수식이 익숙하지 않다면 이 절은 건너뛰어도 됩니다.</p>
<p><strong>① 기본 아이디어</strong></p>
<pre><code>아직 채택하지 않은 사람 중 올해 채택하는 비율 = p + q × (지금까지의 채택 비율)</code></pre>
<p>지금까지의 채택 비율이 0이면 p만큼만 채택하고, 채택 비율이 높아질수록 q만큼 더 채택합니다.</p>
<p><strong>② 연 단위 계산식 (추정에 자주 쓰는 형태)</strong></p>
<pre><code>올해 신규 채택자 n(t) = [ p + q × N(t-1) / m ] × [ m − N(t-1) ]
                     = (올해의 채택률)          × (아직 채택하지 않은 사람 수)</code></pre>
<p>N(t-1)은 작년까지의 누적 채택자입니다. 이 식을 풀어 쓰면 N(t-1)에 대한 2차식이 됩니다.</p>
<pre><code>n(t) = p·m + (q − p)·N(t-1) − (q/m)·N(t-1)²
     =  a  +     b ·N(t-1)  +    c ·N(t-1)²</code></pre>
<p><strong>③ 누적 곡선 (그래프를 그릴 때 쓰는 형태)</strong></p>
<pre><code>F(t) = [1 − e^{−(p+q)t}] / [1 + (q/p)·e^{−(p+q)t}]      (누적 채택 비율)
N(t) = m × F(t)                                        (누적 채택자)</code></pre>
<p><strong>④ 정점 공식</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>항목</th>
<th>공식</th>
<th>뜻</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>정점 시점</td>
<td>ln(q/p) / (p + q)</td>
<td>연간 신규 채택이 가장 많은 시점</td>
</tr>
<tr class="even">
<td>정점 규모</td>
<td>m(p + q)² / 4q</td>
<td>정점 연도의 신규 채택 수</td>
</tr>
<tr class="odd">
<td>정점의 도달률</td>
<td>(q − p) / 2q</td>
<td>q가 p보다 훨씬 크면 약 50%</td>
</tr>
</tbody>
</table>
<p>q가 p보다 크면 S자 모양이 되고, p가 q보다 크면 처음에 가장 많이 채택하고 점점 줄어드는 모양이 됩니다.</p>
<hr>
</section>
</section>
<section id="언제-잘-맞고-언제-조심해야-하는가" class="level2">
<h2 class="anchored" data-anchor-id="언제-잘-맞고-언제-조심해야-하는가">3. 언제 잘 맞고, 언제 조심해야 하는가</h2>
<section id="기본-bass-모형의-네-가지-가정" class="level3">
<h3 class="anchored" data-anchor-id="기본-bass-모형의-네-가지-가정">3.1 기본 Bass 모형의 네 가지 가정</h3>
<p>Bass 모형은 다음을 전제로 합니다. 이 가정이 내 자료와 얼마나 다른지가 결과를 믿을 수 있는지를 좌우합니다.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>가정</th>
<th>쉽게 말하면</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>한 사람은 <strong>한 번만</strong> 채택한다</td>
<td>두 번째 구매·재방문은 세지 않는다</td>
</tr>
<tr class="even">
<td>잠재시장 m은 <strong>고정</strong>되어 있다</td>
<td>천장의 높이가 처음부터 정해져 있다</td>
</tr>
<tr class="odd">
<td><strong>공급 제약이 없다</strong></td>
<td>원하는 사람은 언제든 채택할 수 있다 (물건이 모자라지 않는다)</td>
</tr>
<tr class="even">
<td>p와 q는 <strong>일정</strong>하다</td>
<td>광고·입소문의 힘이 기간 내내 같다</td>
</tr>
</tbody>
</table>
</section>
<section id="잘-맞는-경우" class="level3">
<h3 class="anchored" data-anchor-id="잘-맞는-경우">3.2 잘 맞는 경우</h3>
<p>한 번 사면 끝나는 <strong>내구재</strong>나 <strong>가입형 서비스</strong>처럼, 모집단이 정해져 있고 공급 병목이 없는 경우입니다. TV, 스마트폰, 초고속 인터넷 보급이 교과서적인 사례입니다.</p>
</section>
<section id="조심해야-하는-경우" class="level3">
<h3 class="anchored" data-anchor-id="조심해야-하는-경우">3.3 조심해야 하는 경우</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>상황</th>
<th>무엇이 문제인가</th>
<th>템플스테이에서는</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>재구매·재방문이 섞인 자료</td>
<td>포화가 늦게 오고, m의 뜻이 모호해짐</td>
<td>재참가자가 해마다 새로 세어짐</td>
</tr>
<tr class="even">
<td>공급이 계속 늘어난 시장</td>
<td>시장이 커지는 것을 모형이 알지 못함</td>
<td>운영 사찰이 33곳 → 150곳 이상으로 증가</td>
</tr>
<tr class="odd">
<td>공급이 수요를 막는 시장</td>
<td>공급이 멈춘 시기를 “포화”로 착각</td>
<td>2011~2016년 사찰 수 정체기</td>
</tr>
<tr class="even">
<td>외부 충격이 있는 시기</td>
<td>추정이 불안정해짐</td>
<td>코로나19 (2020~2021)</td>
</tr>
<tr class="odd">
<td>정점 이전 자료만 있을 때</td>
<td>천장 m을 거의 알 수 없음</td>
<td>5장 5단계에서 확인</td>
</tr>
</tbody>
</table>
</section>
<section id="데이터가-갖춰야-할-최소-요건" class="level3">
<h3 class="anchored" data-anchor-id="데이터가-갖춰야-할-최소-요건">3.4 데이터가 갖춰야 할 최소 요건</h3>
<ul class="task-list">
<li><label><input type="checkbox"><strong>무엇을 셌는지 명확하다:</strong> 사람 수인가, 건수인가, 연인원인가?</label></li>
<li><label><input type="checkbox"><strong>도입 초기부터 관측했다:</strong> 앞부분이 빠졌다면 도입 시점과 빠진 기간의 누적값이라도 알아야 한다</label></li>
<li><label><input type="checkbox"><strong>정점 전후가 관측됐다:</strong> 정점 이전 자료만으로는 천장(m)이 크게 흔들린다</label></li>
<li><label><input type="checkbox"><strong>이상 연도를 알고 있다:</strong> 특수 이벤트, 외부 충격이 있었던 해</label></li>
<li><label><input type="checkbox"><strong>공급·가격·정책 변수도 함께 있다:</strong> 모형을 확장하거나 결과를 해석할 때 필요하다</label></li>
</ul>
<blockquote class="blockquote">
<p><strong>“그래도 Bass 모형이 쓸모 있는 곳”</strong> 가정이 맞지 않아 <strong>점 예측</strong>(내년에 정확히 몇 명)에는 약하더라도, 다음 용도로는 여전히 유용합니다. - 확산이 광고(p)와 입소문(q) 중 어디에 기대는지 <strong>구조를 해석</strong>하는 틀 - “천장이 이 정도라면”을 가정해 보는 <strong>시나리오 분석</strong> - 자료가 없는 신제품에 비슷한 제품의 p·q를 빌려 오는 <strong>출시 전 예측</strong></p>
</blockquote>
<hr>
</section>
</section>
<section id="알아두면-좋은-용어" class="level2">
<h2 class="anchored" data-anchor-id="알아두면-좋은-용어">4. 알아두면 좋은 용어</h2>
<p>5장을 읽다가 모르는 말이 나오면 이 장으로 돌아오세요.</p>
<section id="자료에-관한-용어" class="level3">
<h3 class="anchored" data-anchor-id="자료에-관한-용어">4.1 자료에 관한 용어</h3>
<dl>
<dt><strong>순인원 / 연인원</strong></dt>
<dd>
순인원은 참가한 <strong>사람 수</strong>, 연인원은 <strong>사람 수 × 참가 일수</strong>입니다. 1박 2일 참가자 1명은 순인원 1명, 연인원 2명입니다.
</dd>
<dt><strong>신규 n(t) / 누적 N(t)</strong></dt>
<dd>
n(t)는 그해 새로 채택한 수, N(t)는 그해까지 채택한 수의 합계입니다.
</dd>
<dt><strong>도달률 F(t)</strong></dt>
<dd>
누적 채택자 ÷ 잠재시장(m). “잠재 고객 중 몇 %가 이미 채택했나”입니다.
</dd>
<dt><strong>위상도</strong></dt>
<dd>
가로축에 작년까지의 누적, 세로축에 올해 신규를 놓고 점을 찍은 그림입니다. Bass 모형이 맞는 자료라면 점들이 <strong>뒤집힌 U자</strong> 위에 놓입니다. U자의 꼭짓점이 정점, 오른쪽 끝이 가로축과 만나는 곳이 천장(m)입니다.
</dd>
</dl>
</section>
<section id="추정-방법에-관한-용어" class="level3">
<h3 class="anchored" data-anchor-id="추정-방법에-관한-용어">4.2 추정 방법에 관한 용어</h3>
<p>p, q, m 세 숫자를 자료로부터 계산하는 방법이 여러 가지인데, <strong>방법마다 결과가 크게 달라질 수 있습니다.</strong> 이번 분석의 핵심 발견 중 하나입니다.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>방법</th>
<th>쉽게 말하면</th>
<th>특징</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>OLS</strong> (Bass 1969 방식)</td>
<td>올해 신규를 작년 누적의 2차식으로 놓고 일반 회귀분석으로 계산한 뒤, 계수에서 p·q·m을 거꾸로 풀어냄</td>
<td>가장 간단하지만, m의 불확실성(표준오차)을 바로 알 수 없고 계산이 불가능한 경우도 있음</td>
</tr>
<tr class="even">
<td><strong>누적 NLS</strong></td>
<td>누적 S자 곡선을 누적 자료에 직접 맞춤</td>
<td>곡선이 매끄럽게 맞지만, 불확실성을 실제보다 작게 계산하는 경향</td>
</tr>
<tr class="odd">
<td><strong>증분 NLS</strong> (Srinivasan &amp; Mason 1986)</td>
<td>해마다의 신규 자료에 곡선을 맞춤</td>
<td>연간 자료의 구조에 가장 충실하고 불확실성 계산이 상대적으로 정직함. 대신 계산이 까다로움</td>
</tr>
</tbody>
</table>
<dl>
<dt><strong>OLS (최소제곱법)</strong></dt>
<dd>
실제 값과 예측 값의 차이를 제곱해 더한 값이 가장 작아지게 계수를 정하는 일반적인 회귀분석입니다.
</dd>
<dt><strong>NLS (비선형 최소제곱)</strong></dt>
<dd>
곡선처럼 복잡한 모형에 같은 원리를 적용하는 방법입니다. 컴퓨터가 값을 조금씩 바꿔 가며 반복 계산하는데, <strong>어디서 출발하느냐(시작값)에 따라 답이 달라질 수 있어서</strong> 여러 시작값으로 돌려 가장 잘 맞는 답을 고릅니다(<strong>다중 시작점</strong> 방식). R에서는 <code>nls()</code> 함수입니다.
</dd>
<dt><strong>자기상관 (누적 자료의 함정)</strong></dt>
<dd>
누적값은 과거의 모든 값이 쌓인 것이라, 한 해의 오차가 다음 해 누적값에 그대로 이어집니다. 오차들이 서로 독립적이지 않으면, 컴퓨터는 실제보다 <strong>더 정확하게 추정했다고 착각</strong>합니다. 그래서 누적 NLS의 표준오차는 그대로 믿기 어렵습니다.
</dd>
<dt><strong>더미 변수</strong></dt>
<dd>
특정 기간(예: 코로나 2020~2021년)에만 1, 나머지는 0인 변수입니다. 그 기간의 특수한 효과를 따로 떼어 추정하는 데 씁니다.
</dd>
</dl>
</section>
<section id="모형을-평가하는-용어" class="level3">
<h3 class="anchored" data-anchor-id="모형을-평가하는-용어">4.3 모형을 평가하는 용어</h3>
<dl>
<dt><strong>R² (결정계수)</strong></dt>
<dd>
모형이 실제 값의 오르내림을 몇 %나 설명하는지 나타냅니다(1에 가까울수록 좋음). 단, <strong>이미 있는 자료를 잘 설명한다는 뜻이지, 미래를 잘 맞힌다는 뜻은 아닙니다.</strong>
</dd>
<dt><strong>RSS / RMSE</strong></dt>
<dd>
RSS는 오차를 제곱해 더한 값, RMSE는 평균적인 오차의 크기입니다. 작을수록 좋고, 같은 형태의 모형끼리만 비교해야 공정합니다.
</dd>
<dt><strong>표준오차 (se)</strong></dt>
<dd>
추정값이 얼마나 흔들릴 수 있는지 나타냅니다. 대략 <strong>추정값 ± 2 × 표준오차</strong>가 95% 신뢰구간입니다. <strong>표준오차가 추정값의 절반을 넘으면 사실상 “정해지지 않았다”</strong>고 봐야 합니다.
</dd>
<dt><strong>잔차 그림</strong></dt>
<dd>
해마다 (실제 − 예측)을 그린 그림입니다. 오차가 한쪽(늘 과대 또는 늘 과소)으로 몰리거나 추세가 보이면, 모형의 구조가 자료와 맞지 않는다는 신호입니다.
</dd>
<dt><strong>MAPE (평균 절대 백분율 오차)</strong></dt>
<dd>
예측이 평균적으로 몇 % 빗나갔는지입니다. 20%면 평균 20% 틀렸다는 뜻입니다.
</dd>
</dl>
</section>
<section id="예측을-검증하는-용어" class="level3">
<h3 class="anchored" data-anchor-id="예측을-검증하는-용어">4.4 예측을 검증하는 용어</h3>
<dl>
<dt><strong>표본 내 적합 vs 표본 밖 예측</strong></dt>
<dd>
모형을 만들 때 쓴 자료를 잘 설명하는 것(표본 내)과, 모형이 보지 못한 미래를 맞히는 것(표본 밖)은 <strong>전혀 다른 능력</strong>입니다. 시험 문제를 미리 보고 푼 점수와 처음 보는 문제를 푼 점수가 다른 것과 같습니다. <strong>예측 모형은 반드시 표본 밖에서 평가해야 합니다.</strong>
</dd>
<dt><strong>Holdout 검증</strong></dt>
<dd>
최근 몇 년의 자료를 일부러 숨겨 두고, 그 전까지의 자료로 만든 모형이 숨긴 기간을 맞히는지 보는 방법입니다.
</dd>
<dt><strong>Rolling origin 평가</strong></dt>
<dd>
Holdout을 예측 시작 시점을 한 해씩 옮겨 가며 여러 번 반복하는 것입니다. 한두 번의 시험에 섞이는 운을 줄여 줍니다.
</dd>
</dl>
<pre><code>시험 1: [2002 ─────── 2010 자료로 추정] → 2011 예측
시험 2: [2002 ──────── 2011 자료로 추정] → 2012 예측
시험 3: [2002 ───────── 2012 자료로 추정] → 2013 예측
 ...</code></pre>
<dl>
<dt><strong>벤치마크 (기준선)</strong></dt>
<dd>
복잡한 모형이 <strong>최소한 넘어야 할 단순 예측</strong>입니다. 이것도 못 넘으면 복잡한 모형을 쓸 이유가 없습니다. - <strong>Naive:</strong> “올해도 작년과 같다.” 수준이 안정적일 때 강합니다. - <strong>Drift:</strong> “최근 몇 년의 평균 증가분만큼 계속 늘어난다.” 추세가 안정적일 때 강합니다.
</dd>
<dt><strong>부트스트랩 구간</strong></dt>
<dd>
모형의 오차를 무작위로 다시 뽑아 가상 자료를 수백 번 만들고, 매번 모형을 다시 추정해 예측한 결과의 범위입니다. “추정이 이만큼 흔들리면 예측은 이만큼 흔들린다”를 보여 줍니다.
</dd>
</dl>
</section>
<section id="모형-확장에-관한-용어" class="level3">
<h3 class="anchored" data-anchor-id="모형-확장에-관한-용어">4.5 모형 확장에 관한 용어</h3>
<dl>
<dt><strong>동적 잠재시장 (동적 m)</strong> (Mahajan &amp; Peterson, 1978 계열)</dt>
<dd>
천장 m이 고정값이 아니라 시간에 따라 변하도록 한 모형입니다. 이번에는 <strong>m = k × 사찰 수</strong>로, 사찰이 늘면 천장이 올라갑니다.
</dd>
<dt><strong>k</strong></dt>
<dd>
사찰 1곳이 떠받치는 잠재 참가자 규모입니다.
</dd>
<dt><strong>GBM (Generalized Bass Model)</strong> (Bass, Krishnan &amp; Jain, 1994)</dt>
<dd>
가격·광고·공급 같은 변수가 확산의 <strong>속도</strong>를 조절한다고 본 모형입니다. 천장은 그대로 두고 그 천장에 도달하는 속도를 앞당기거나 늦춥니다.
</dd>
<dt><strong>반복 구매 모형</strong></dt>
<dd>
신규 채택과 재구매를 분리하는 모형입니다. 이번에는 재참가 자료가 없어 적용하지 못했습니다.
</dd>
</dl>
<hr>
</section>
</section>
<section id="실습-템플스테이-자료로-단계별-분석하기" class="level2">
<h2 class="anchored" data-anchor-id="실습-템플스테이-자료로-단계별-분석하기">5. 실습: 템플스테이 자료로 단계별 분석하기</h2>
<section id="출발점-논문과-데이터" class="level3">
<h3 class="anchored" data-anchor-id="출발점-논문과-데이터">5.0 출발점: 논문과 데이터</h3>
<section id="참고-논문" class="level4">
<h4 class="anchored" data-anchor-id="참고-논문">참고 논문</h4>
<blockquote class="blockquote">
<p>강문영 (2024). “Bass 확산 모형을 기반으로 한 템플스테이 수요 예측.” <em>상품학연구</em>, 42(5), 35–39.</p>
</blockquote>
<ul>
<li><strong>자료:</strong> 2002~2023년 연도별 템플스테이 참가자 수</li>
<li><strong>결과:</strong> m = 907.5만 명, p = .01, q = .18 (코로나 이전 2002~2019 자료로는 m = 954.3만 명)</li>
<li><strong>결론:</strong> 2023년 말에 잠재시장의 77%에 도달했고, 앞으로 연간 증가율이 급감하므로 수요 감소에 대비해야 한다</li>
</ul>
<p><strong>처음 읽을 때 생긴 의문 네 가지</strong></p>
<ol type="1">
<li><strong>다시 오는 참가자</strong>가 섞인 서비스에, “한 사람은 한 번만”을 가정하는 모형을 그대로 썼다.</li>
<li>운영 사찰이 33곳에서 150곳으로 늘어난 <strong>공급 확대</strong>를 고려하지 않았다.</li>
<li>논문 표 1을 보면 <strong>13개 연도 모두에서 예측이 실제보다 높다.</strong> 우연이라면 높고 낮음이 섞여야 한다.</li>
<li>어떤 추정 방법을 썼는지, 추정이 얼마나 불확실한지(표준오차)를 밝히지 않았다.</li>
</ol>
</section>
<section id="데이터" class="level4">
<h4 class="anchored" data-anchor-id="데이터">데이터</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>자료</th>
<th>기간</th>
<th>내용</th>
<th>출처</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>템플스테이 20년사</td>
<td>2002~2021</td>
<td>사찰 수, 순인원·연인원 (내국인/외국인/합계)</td>
<td>한국불교문화사업단, 『템플스테이 20년사』 p.272</td>
</tr>
<tr class="even">
<td>연합뉴스 기사 표</td>
<td>2016~2025</td>
<td>사찰 수, 순인원 (내국인/외국인/합계), 2002~2025 누적</td>
<td>연합뉴스 AKR20260115161800005 (한국불교문화사업단 제공)</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>연합뉴스 표에는 “재판매 및 DB 금지” 표기가 있습니다. 내부 학습·참고용으로 쓰되, 외부 배포나 데이터베이스화는 피하고 출처를 반드시 밝혀 주세요.</p>
</blockquote>
</section>
<section id="가장-먼저-확인해야-했던-것-무엇을-셌는가" class="level4">
<h4 class="anchored" data-anchor-id="가장-먼저-확인해야-했던-것-무엇을-셌는가">가장 먼저 확인해야 했던 것: 무엇을 셌는가</h4>
<p>처음에는 연합뉴스 수치가 논문 수치의 <strong>절반 정도</strong>여서 혼란스러웠습니다. 20년사를 확인해 보니 이유는 단순했습니다.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>구분</th>
<th>뜻</th>
<th>1박 2일 참가자 1명이면</th>
<th>사용한 곳</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>순인원</strong></td>
<td>참가한 사람 수</td>
<td>1명</td>
<td>연합뉴스</td>
</tr>
<tr class="even">
<td><strong>연인원</strong></td>
<td>사람 수 × 참가 일수</td>
<td>2명</td>
<td><strong>논문</strong></td>
</tr>
</tbody>
</table>
<p>연인원을 2002~2011년까지 더하면 204.9만 명으로, 논문 표 1의 2011년 누적과 정확히 일치했습니다.</p>
<p><strong>이번 분석은 순인원을 씁니다.</strong> 이유는 두 가지입니다.</p>
<ul>
<li>Bass 모형의 m은 <strong>“사람 수”</strong>이므로 순인원이 모형의 뜻에 더 가깝습니다.</li>
<li>연인원 ÷ 순인원 비율이 2002년 4.6에서 2017년 1.8로 변했습니다. 연인원을 쓰면 <strong>체류 일수가 줄어든 변화가 수요 변화처럼 섞여</strong> 들어갑니다.</li>
</ul>
<p>다만 순인원도 <strong>다른 해에 다시 온 사람을 새로 셉니다.</strong> 엄밀한 의미의 “채택자(처음 참가한 사람)”와는 다르다는 점을 기억해 두세요.</p>
</section>
<section id="데이터-검증" class="level4">
<h4 class="anchored" data-anchor-id="데이터-검증">데이터 검증</h4>
<ul>
<li>20년사의 누적 합계 6개(순인원·연인원 × 내국인·외국인·합계)가 모두 연도별 값의 합과 일치했습니다.</li>
<li>20년사 2002~2021 순인원 합계(2,998,073)에 연합뉴스 2022~2025 값을 더하면 4,184,373으로, 연합뉴스 표의 2002~2025 누적과 <strong>정확히 일치</strong>합니다.</li>
<li><strong>불일치 1건:</strong> 2019년 내국인 순인원이 20년사에는 247,783, 연합뉴스에는 247,738입니다. 247,738 + 외국인 47,058 = 합계 294,796이 되므로 <strong>247,738로 정정</strong>했습니다(차이 45명, 분석 영향 없음).</li>
<li>통합 자료: <code>templestay_2002to2025.csv</code> (순인원 2002~2025, 연인원 2002~2021, 사찰 수)</li>
</ul>
<blockquote class="blockquote">
<p><strong>교훈:</strong> 모형을 돌리기 전에 <strong>자료의 정의(무엇을 셌는가)</strong>부터 확인하세요. 이 확인 하나로 논문과 숫자가 다른 이유가 풀렸고, 어떤 자료가 모형에 더 맞는지도 정해졌습니다.</p>
</blockquote>
<details>
<summary>
(참고) 분석 설계가 바뀐 과정
</summary>
<p>처음에는 연합뉴스 자료(2016~2025, 10년치)만 있어서, 앞 14년이 잘린 자료로 분석하는 방법을 검토했습니다. 이때 정답을 아는 <strong>가상 자료로 모의실험</strong>을 해서 세 가지를 확인했습니다.</p>
<ul>
<li>정점 이전 자료로는 m이 크게 흔들린다.</li>
<li>OLS는 앞이 잘린 자료에서 p를 거의 추정하지 못한다.</li>
<li>NLS는 도입 시점과 관측 직전 누적값을 알면 잘린 자료에서도 비교적 잘 추정한다.</li>
</ul>
<p>이후 20년사 자료를 확보해 <strong>2002~2025년 24개 연도의 완전한 계열</strong>을 만들 수 있게 되었고, 혼란을 피하려고 모의실험 결과는 정리했습니다. 아래 분석은 모두 완전한 계열을 이용했습니다.</p>
</details>
<hr>
</section>
</section>
<section id="전체-흐름" class="level3">
<h3 class="anchored" data-anchor-id="전체-흐름">5.1 전체 흐름</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>단계</th>
<th>스크립트</th>
<th>알고 싶은 것</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><code>01_data_explore.R</code></td>
<td>모형을 돌리기 전에, 자료는 어떤 모양인가?</td>
</tr>
<tr class="even">
<td>2</td>
<td><code>02_bass_fit.R</code></td>
<td>계산 방법에 따라 p·q·m이 얼마나 다른가?</td>
</tr>
<tr class="odd">
<td>3</td>
<td><code>03_specification.R</code></td>
<td>분석자의 선택(출발 연도, 코로나 처리)이 결과를 얼마나 바꾸는가?</td>
</tr>
<tr class="even">
<td>4</td>
<td><code>04_forecast_validate.R</code></td>
<td>처음 보는 기간도 잘 맞히는가? 논문은 정확히 어떻게 계산했나?</td>
</tr>
<tr class="odd">
<td>5</td>
<td><code>05_rolling_origin.R</code></td>
<td>자료가 쌓일수록 추정이 안정되는가?</td>
</tr>
<tr class="even">
<td>6</td>
<td><code>06_supply_scenarios.R</code></td>
<td>공급(사찰 수)을 반영하면 어떻게 달라지는가? 정책 시나리오별로는?</td>
</tr>
</tbody>
</table>
<p><strong>단위는 모두 만 명(순인원)</strong>이고, 2002년을 1년차로 놓습니다(3단계 비교 제외).</p>
<hr>
</section>
<section id="단계-자료-살펴보기" class="level3">
<h3 class="anchored" data-anchor-id="단계-자료-살펴보기">5.2 1단계: 자료 살펴보기</h3>
<p><strong>알고 싶은 것:</strong> 모형을 적용하기 전에 자료의 모양을 눈으로 봅니다. S자 곡선인지, 정점을 지났는지, 이상한 해는 언제인지, 공급과 어떤 관계인지 확인합니다.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="out/01_fig1_overview.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="1단계 개요"><img src="out/01_fig1_overview.png" class="img-fluid figure-img" alt="1단계 개요"></a></p>
<figcaption>1단계 개요</figcaption>
</figure>
</div>
<p><strong>발견 ① 아직 정점을 지나지 않았다</strong></p>
<ul>
<li>누적값은 원래 줄어들 수 없으니, “누적이 늘고 있다”는 것만으로는 정점을 판단할 수 없습니다.</li>
<li>정점은 <strong>해마다의 신규 참가자 수(누적 곡선의 기울기)</strong>로 판단해야 합니다. 연간 순인원은 2025년(34.9만)이 역대 최대이고, 누적 곡선도 아직 가팔라지는 모양입니다.</li>
<li><strong>한 해 줄었다고 정점은 아닙니다.</strong> 2012년(−19.8%)과 2020년(−61%)의 감소는 모두 정점이 아니었습니다. 감소가 <strong>계속되는지</strong> 봐야 합니다.</li>
</ul>
<p><strong>발견 ② 공급과 수요가 함께 움직였다</strong></p>
<ul>
<li>2003→2019년 연평균 증가율은 참가자(순인원) 14.2%, 사찰 수 14.4%로 거의 같고, 두 계열의 상관은 r = .95입니다.</li>
<li>참가자 증가를 “사찰 수 증가 × 사찰당 참가자 증가”로 나눠 보면, 2005→2019년에 사찰 수는 약 3.3배, 사찰당 순인원은 약 1.7배(1,282명 → 2,152명) 늘었습니다. <strong>증가의 큰 몫은 공급 확대</strong>에서 왔고, 사찰당 수요도 함께 늘었습니다.</li>
<li>단, <strong>어느 쪽이 원인인지는 알 수 없습니다.</strong> 수요가 있어서 사찰이 참여했을 수도 있습니다.</li>
</ul>
<p><strong>발견 ③ 공급이 멈추면 수요도 멈췄다</strong></p>
<p>2011~2016년 사찰 수는 118곳 → 123곳으로 사실상 멈췄고, 참가자도 21만 명 안팎에서 맴돌았습니다. 2017년 사찰이 14곳 늘자 참가자가 24% 뛰었습니다.</p>
<p><strong>발견 ④ 이상한 해</strong></p>
<p>2002년(월드컵 특수, 외국인 49%), 2012년(사찰 수 감소), 2020~2021년(코로나, −61%)</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="out/01_fig2_phase.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Bass 위상도"><img src="out/01_fig2_phase.png" class="img-fluid figure-img" alt="Bass 위상도"></a></p>
<figcaption>Bass 위상도</figcaption>
</figure>
</div>
<p><strong>위상도 읽는 법</strong></p>
<ul>
<li>가로축은 작년까지의 누적, 세로축은 올해 신규입니다.</li>
<li>Bass 모형이 맞다면 점들이 <strong>뒤집힌 U자(포물선)</strong> 위에 놓여야 합니다. 꼭짓점이 정점, 오른쪽 끝이 천장(m)입니다.</li>
<li>2019년까지는 점들이 포물선처럼 꺾이는 모양이었습니다. 코로나 연도를 빼고 그린 것이라 <strong>코로나 탓은 아니고</strong>, 상당 부분 <strong>2011~2016년의 공급 정체</strong>가 만든 모양일 수 있습니다.</li>
<li>코로나 이후 2022~2025년 점들은 그 곡선 위로 다시 올라갔습니다. 2010년대의 둔화를 “포화”의 신호로 보기 어렵게 만드는 대목입니다.</li>
</ul>
<blockquote class="blockquote">
<p><strong>1단계 요약:</strong> 자료는 아직 정점 전이고, 공급과 강하게 함께 움직입니다. 공급이 멈춘 시기의 둔화를 포화로 착각하지 않도록 조심해야 합니다.</p>
</blockquote>
<hr>
</section>
<section id="단계-세-가지-방법으로-기본-추정" class="level3">
<h3 class="anchored" data-anchor-id="단계-세-가지-방법으로-기본-추정">5.3 2단계: 세 가지 방법으로 기본 추정</h3>
<p><strong>알고 싶은 것:</strong> 같은 자료에 계산 방법만 바꾸면 결과가 얼마나 달라지는가?</p>
<p><strong>설정:</strong> 순인원 2002~2025, 코로나 포함, 아무것도 손대지 않은 기본형</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>방법</th>
<th>p</th>
<th>q</th>
<th>m (표준오차)</th>
<th>모형이 말하는 정점</th>
<th>2025년 도달률</th>
<th>R²</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OLS</td>
<td>.0086</td>
<td>.131</td>
<td>734 (–)</td>
<td>2020.6</td>
<td>57%</td>
<td>.63</td>
</tr>
<tr class="even">
<td>누적 NLS</td>
<td>.0068</td>
<td>.181</td>
<td>524 (±34)</td>
<td>2018.5</td>
<td>80%</td>
<td>.59</td>
</tr>
<tr class="odd">
<td>증분 NLS</td>
<td>.0066</td>
<td>.116</td>
<td>858 (±326)</td>
<td>2024.3</td>
<td>49%</td>
<td>.68</td>
</tr>
</tbody>
</table>
<p><strong>표 읽는 법:</strong> m은 “앞으로 언젠가 참가할 총인원(만 명)”, 도달률은 “모형이 보기에 그중 몇 %가 2025년까지 이미 참가했나”입니다.</p>
<p><img src="out/02_fig1_fit.png" class="img-fluid" alt="2단계 적합"> <img src="out/02_fig2_residuals.png" class="img-fluid" alt="2단계 잔차"></p>
<p><strong>해석</strong></p>
<ol type="1">
<li><strong>p와 q는 비슷한데 m이 크게 갈립니다.</strong> 방법에 따라 천장이 524만~858만 명으로 달라집니다.</li>
<li><strong>q가 커 보이는 데는 함정이 있습니다.</strong> q/p가 15~27로 입소문 효과가 강해 보이지만, Bass 모형에는 공급 변수가 없어서 <strong>사찰 증가로 생긴 성장까지 입소문(q)이 떠안았을</strong> 가능성이 큽니다. 6단계에서 확인합니다.</li>
<li><strong>m은 사실상 정해지지 않았습니다.</strong> 증분 NLS의 m 표준오차가 326이라 95% 구간이 대략 200만~1,500만 명입니다. “천장이 200만일 수도, 1,500만일 수도 있다”는 뜻입니다. OLS에서도 곡선의 휘어짐을 나타내는 2차항이 유의확률 .098로 약합니다.</li>
<li><strong>누적 NLS의 작은 표준오차(±34)는 믿기 어렵습니다.</strong> 4장에서 설명한 누적 자료의 자기상관 때문에 실제보다 작게 계산된 것입니다. 이 모형은 “2018년이 정점, 이미 80% 도달”이라고 하는데, 2024~2025년의 역대 최다 기록과 맞지 않습니다.</li>
<li><strong>오차에 일정한 패턴이 있습니다.</strong> 초기에는 모든 모형이 실제보다 높게, 2022~2025년에는 모두 실제보다 낮게 예측했고 그 차이가 점점 커집니다. 실제 성장은 Bass 곡선보다 <strong>완만하고 오래 이어지는</strong> 모양이라는 뜻입니다.</li>
</ol>
<blockquote class="blockquote">
<p><strong>2단계 요약:</strong> 계산 방법에 따라 천장이 크게 달라지고, 어느 방법도 최근의 성장을 따라가지 못합니다.</p>
</blockquote>
<hr>
</section>
<section id="단계-분석-설정을-바꿔-보기" class="level3">
<h3 class="anchored" data-anchor-id="단계-분석-설정을-바꿔-보기">5.4 3단계: 분석 설정을 바꿔 보기</h3>
<p><strong>알고 싶은 것:</strong> 분석자가 내리는 선택이 결과를 얼마나 바꾸는가?</p>
<p><strong>바꿔 본 선택</strong></p>
<ul>
<li>출발 연도: 2002년(월드컵 특수 포함) vs 2003년</li>
<li>코로나 2020~2021년: ① 그대로 포함 ② 빼고 분석 ③ 더미 변수로 따로 처리</li>
</ul>
<p>이렇게 2 × 3 = 6가지 설정으로 돌렸습니다.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>방법</th>
<th>6가지 설정에서 m의 범위</th>
<th>정점 범위</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>누적 NLS</td>
<td>509 ~ 547</td>
<td>2018년</td>
</tr>
<tr class="even">
<td>OLS</td>
<td>724 ~ 789</td>
<td>2020~2022년</td>
</tr>
<tr class="odd">
<td>증분 NLS</td>
<td>790 ~ 942</td>
<td>2022~2026년</td>
</tr>
</tbody>
</table>
<p><img src="out/03_fig1_m_by_spec.png" class="img-fluid" alt="3단계 설정별 m"> <img src="out/03_fig2_curves_nls_inc.png" class="img-fluid" alt="3단계 곡선"></p>
<p><strong>해석</strong></p>
<ol type="1">
<li><strong>계산 방법의 선택이 설정의 선택보다 훨씬 중요합니다.</strong> 설정을 바꾸면 m이 40만~150만 명 움직이지만, 방법을 바꾸면 300만~400만 명이 달라집니다.</li>
<li><strong>출발 연도의 영향은 작습니다.</strong> 2002년 참가자가 0.26만 명뿐이라 모형에 주는 무게가 작습니다.</li>
<li><strong>코로나를 빼면 추정이 정밀해집니다.</strong> 증분 NLS의 m 표준오차가 326에서 103으로 줄었습니다. 급감한 두 해가 곡선을 눌러 m을 흔들고 있었던 것입니다.</li>
<li><strong>더미로 처리한 결과는 빼고 분석한 결과와 거의 같습니다.</strong> 더미를 넣으면 코로나 두 해는 자기만의 값을 갖게 되어 p·q·m 계산에 영향을 주지 않기 때문입니다. 더미가 잡아낸 코로나 효과는 OLS에서 약 −18만 명, 증분 NLS에서 약 61% 감소입니다.
<ul>
<li>두 더미가 가정하는 상황은 다릅니다. OLS 더미는 “코로나로 못 온 사람이 잠재 참가자로 남아 있다”고 보고, 증분 NLS 더미는 “확산의 시계는 그대로 흐르고, 코로나로 사라진 참가자는 돌아오지 않는다”고 봅니다.</li>
</ul></li>
<li><strong>어떤 설정도 핵심 문제를 풀지 못했습니다.</strong> 모든 곡선이 2022~2023년 무렵 정점을 찍고 내려가는데, 실제 2024~2025년은 곡선보다 위에 있습니다. 문제는 자료 처리가 아니라 <strong>모형의 구조</strong>에 있습니다.</li>
</ol>
<blockquote class="blockquote">
<p><strong>3단계 요약:</strong> 설정을 바꿔서는 해결되지 않습니다. 모형 자체의 가정을 다시 봐야 합니다.</p>
</blockquote>
<hr>
</section>
<section id="단계-예측-시험과-논문-재현" class="level3">
<h3 class="anchored" data-anchor-id="단계-예측-시험과-논문-재현">5.5 4단계: 예측 시험과 논문 재현</h3>
<section id="part-a.-처음-보는-기간을-맞히는가-holdout-검증" class="level4">
<h4 class="anchored" data-anchor-id="part-a.-처음-보는-기간을-맞히는가-holdout-검증">Part A. 처음 보는 기간을 맞히는가 (Holdout 검증)</h4>
<p>두 번 시험했습니다.</p>
<ul>
<li><strong>시험 1:</strong> 2015년까지 자료로 모형을 만들고 → 2016~2019년을 예측</li>
<li><strong>시험 2:</strong> 2019년까지 자료로 모형을 만들고 → 2022~2025년을 예측 (2020~2021년은 코로나라 채점에서 제외)</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th>예측 방법</th>
<th>시험 1 오차 (MAPE)</th>
<th>시험 2 오차 (MAPE)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OLS</td>
<td>55.6%</td>
<td>27.2%</td>
</tr>
<tr class="even">
<td>누적 NLS</td>
<td>58.0%</td>
<td>43.9%</td>
</tr>
<tr class="odd">
<td>증분 NLS</td>
<td>48.0%</td>
<td>23.5%</td>
</tr>
<tr class="even">
<td><strong>Naive</strong> (작년 값 유지)</td>
<td>20.5%</td>
<td><strong>16.2%</strong></td>
</tr>
<tr class="odd">
<td><strong>Drift</strong> (최근 추세 연장)</td>
<td><strong>13.4%</strong></td>
<td>33.2%</td>
</tr>
</tbody>
</table>
<p>(오차가 작을수록 좋습니다. 굵은 글씨가 각 시험의 1위)</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="out/04_fig1_holdout.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="4단계 holdout"><img src="out/04_fig1_holdout.png" class="img-fluid figure-img" alt="4단계 holdout"></a></p>
<figcaption>4단계 holdout</figcaption>
</figure>
</div>
<p><strong>해석</strong></p>
<ol type="1">
<li><strong>Bass 모형 세 가지가 모두 단순 예측에 졌습니다.</strong></li>
<li><strong>2015년까지의 자료로 만든 모형은 급감을 예측했습니다.</strong> 이 모형이 추정한 천장(230만~257만 명)은 2019년 실제 누적(276만 명)보다도 작았습니다. 2011~2016년의 <strong>공급 정체를 포화로 잘못 읽은</strong> 결과입니다.</li>
<li><strong>Naive와 Drift의 순위가 뒤바뀐 이유:</strong> 시험 2에서 두 방법 모두 코로나를 전혀 모르는 상태였습니다.
<ul>
<li>Drift는 코로나로 멈춘 기간에도 성장이 계속된다고 가정해서 <strong>높게</strong> 예측했습니다.</li>
<li>Naive는 코로나 이후 실적이 마침 2019년 수준(29.5만) 근처를 오가서 <strong>운 좋게</strong> 오차가 작았습니다.</li>
<li>어느 벤치마크가 늘 더 좋은 것은 아닙니다. 둘 다 “복잡한 모형이 최소한 넘어야 할 기준선”입니다.</li>
</ul></li>
</ol>
</section>
<section id="part-b.-논문은-어떻게-계산했나-재현" class="level4">
<h4 class="anchored" data-anchor-id="part-b.-논문은-어떻게-계산했나-재현">Part B. 논문은 어떻게 계산했나 (재현)</h4>
<p>논문과 같은 <strong>연인원</strong> 자료(20년사 2002~2021 + 논문 표 1에서 역산한 2022년 43.0만, 2023년 54.6만)로 세 방법을 돌렸습니다.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>추정 기간</th>
<th>논문</th>
<th><strong>OLS (재현)</strong></th>
<th>누적 NLS</th>
<th>증분 NLS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2002~2023</td>
<td>m 907.5, p .01, q .18</td>
<td><strong>m 908.0, p .012, q .179</strong></td>
<td>m 841</td>
<td>m 972</td>
</tr>
<tr class="even">
<td>2002~2019</td>
<td>m 954.3</td>
<td><strong>m 955.0</strong></td>
<td>m 805</td>
<td>m 1,044</td>
</tr>
</tbody>
</table>
<p>→ OLS의 결과가 논문과 거의 같습니다. <strong>논문은 OLS(Bass 1969 방식)를 썼습니다.</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="out/04_fig2_paper_replication.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="4단계 논문 재현"><img src="out/04_fig2_paper_replication.png" class="img-fluid figure-img" alt="4단계 논문 재현"></a></p>
<figcaption>4단계 논문 재현</figcaption>
</figure>
</div>
<p><strong>논문의 예측값은 어떻게 만들어졌나</strong></p>
<ul>
<li>논문 표 1(예측 누적)은 13개 연도 모두 0.2만 명 이내로, 표 2(2049년까지 예측)도 0.5만 명 이내로 재현됐습니다.</li>
<li>재현해 보니 논문의 “예측 누적”은 <strong>누적 0에서 출발해 추정식을 매년 반복 적용해 만든 가상 경로</strong>였습니다.</li>
</ul>
<blockquote class="blockquote">
<p><strong>두 가지 예측 방식의 차이 (비유)</strong> - <strong>한 해씩 예측:</strong> 매년 실제 위치를 확인하고, 거기서 1년 뒤를 예측합니다. 내비게이션이 매번 GPS로 현재 위치를 다시 잡는 것과 같습니다. - <strong>0에서 출발한 가상 경로:</strong> 출발점에서 방향과 속도만으로 계속 계산해 나갑니다. 초반에 조금만 어긋나도 오차가 계속 쌓입니다.</p>
</blockquote>
<ul>
<li><strong>“13개 연도 모두 과대추정”의 원인:</strong> 모형이 틀려서라기보다, 초기 몇 년의 과대추정이 가상 경로에 <strong>계속 쌓여서</strong> 이후 모든 연도로 이어진 것입니다. 논문 표 1의 오차(Diff %)는 모형의 정확도라기보다 <strong>경로가 벗어난 정도</strong>입니다.</li>
<li><strong>논문 모형의 예측과 현실:</strong> 논문 모형은 연간 연인원이 2023년 33.0만 → 2024년 29.4만 → 2025년 25.9만으로 <strong>줄어든다</strong>고 봤습니다. 실제 2023년 연인원은 이미 54.6만이었고, 순인원은 2024~2025년에 역대 최다를 경신했습니다.</li>
</ul>
<blockquote class="blockquote">
<p><strong>4단계 요약:</strong> 표준 Bass 모형은 “작년 값 그대로”라는 가장 단순한 예측도 이기지 못했습니다. 논문의 방법은 재현됐지만, 그 예측은 현실과 달랐습니다.</p>
</blockquote>
<hr>
</section>
</section>
<section id="단계-자료가-쌓일수록-추정이-안정되는가-rolling-origin" class="level3">
<h3 class="anchored" data-anchor-id="단계-자료가-쌓일수록-추정이-안정되는가-rolling-origin">5.6 5단계: 자료가 쌓일수록 추정이 안정되는가 (Rolling origin)</h3>
<p><strong>알고 싶은 것:</strong> 해마다 새 자료가 들어올 때, 모형이 추정하는 천장(m)과 정점이 한 값으로 모이는가?</p>
<p><strong>방법:</strong> 관측 끝 연도를 2008, 2009, …, 2025년으로 한 해씩 늘려 가며, 매번 2002년부터 그해까지의 자료로 다시 추정했습니다. (코로나 연도는 추정에서 빼므로 2020, 2021년 추정은 2019년과 같습니다.)</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>관측 끝</th>
<th>실제 누적</th>
<th>증분 NLS의 m</th>
<th>m ÷ 누적</th>
<th>모형이 말하는 정점</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2011</td>
<td>92</td>
<td>357</td>
<td>3.9배</td>
<td>2014.1</td>
</tr>
<tr class="even">
<td>2012</td>
<td>109</td>
<td>178</td>
<td>1.6배</td>
<td>2010.9</td>
</tr>
<tr class="odd">
<td>2016</td>
<td>190</td>
<td>301</td>
<td>1.6배</td>
<td>2013.7</td>
</tr>
<tr class="even">
<td>2019</td>
<td>276</td>
<td>599</td>
<td>2.2배</td>
<td>2019.3</td>
</tr>
<tr class="odd">
<td>2025</td>
<td>418</td>
<td>790</td>
<td>1.9배</td>
<td>2022.4</td>
</tr>
</tbody>
</table>
<p><img src="out/05_fig1_m_path.png" class="img-fluid" alt="5단계 m 궤적"> <img src="out/05_fig2_peak_path.png" class="img-fluid" alt="5단계 정점 궤적"> <img src="out/05_fig3_curves.png" class="img-fluid" alt="5단계 곡선"></p>
<p><strong>해석</strong></p>
<ol type="1">
<li><strong>천장 m이 한 값으로 모이지 않고, 누적을 뒤쫓아 올라갑니다.</strong> 좋은 모형이라면 자료가 쌓일수록 m이 어떤 값으로 안정되어야 합니다. 그런데 m은 계속 “그 시점 누적의 약 1.2~2배”를 따라 올라갔습니다. 2012년 한 해의 감소만으로 m이 357만에서 178만으로 반토막 나기도 했습니다.</li>
<li><strong>모형은 거의 늘 “정점은 이미 지났다”고 말합니다.</strong> 정점 그래프에서 점들이 대각선(“정점 = 관측 끝 연도”) 아래에 있다는 것이 그 뜻입니다. 2025년까지의 자료로도 정점을 2018~2022년으로 보지만, 실제 연간 최대는 2025년입니다.</li>
<li><strong>“곧 감소”를 반복하다가 밀려납니다.</strong> 각 시점의 곡선이 “지금이 정점 근처, 곧 감소”를 말하고, 새 자료가 들어오면 곡선이 오른쪽 위로 밀려나는 일이 반복됩니다.</li>
</ol>
<p><strong>여러 번 시험한 예측 오차</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>모형</th>
<th>1년 앞 오차 (15회 평균)</th>
<th>3년 앞 오차 (13회 평균)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OLS</td>
<td>22.1%</td>
<td>41.8%</td>
</tr>
<tr class="even">
<td>누적 NLS</td>
<td>30.6%</td>
<td>43.9%</td>
</tr>
<tr class="odd">
<td>증분 NLS</td>
<td>20.3%</td>
<td>38.7%</td>
</tr>
<tr class="even">
<td><strong>Naive</strong></td>
<td>14.7%</td>
<td><strong>30.3%</strong></td>
</tr>
<tr class="odd">
<td><strong>Drift</strong></td>
<td><strong>13.3%</strong></td>
<td>36.2%</td>
</tr>
</tbody>
</table>
<p>1년 앞 예측에서 가장 정확했던 횟수는 Naive 6회, Drift 4회, OLS 3회, 누적 NLS 2회였습니다. 여러 번 시험해도 4단계와 같은 결론이므로, <strong>4단계 결과는 운이 아니었습니다.</strong></p>
<blockquote class="blockquote">
<p><strong>5단계 요약:</strong> 자료가 쌓여도 천장 추정이 안정되지 않고, 모형은 매번 “포화가 임박했다”고 잘못 말합니다. 이것은 가정(고정된 천장)이 자료와 맞지 않는다는 강한 신호입니다.</p>
</blockquote>
<hr>
</section>
<section id="단계-공급을-반영한-모형과-정책-시나리오" class="level3">
<h3 class="anchored" data-anchor-id="단계-공급을-반영한-모형과-정책-시나리오">5.7 6단계: 공급을 반영한 모형과 정책 시나리오</h3>
<p><strong>알고 싶은 것:</strong> “사찰 수를 그대로 두면 수요는 어디서 멈추고, 사찰을 늘리면 그 천장이 얼마나 올라가는가?”</p>
<section id="세-모형-비교-순인원-코로나-제외" class="level4">
<h4 class="anchored" data-anchor-id="세-모형-비교-순인원-코로나-제외">세 모형 비교 (순인원, 코로나 제외)</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>모형</th>
<th>가정</th>
<th>p</th>
<th>q</th>
<th>잠재시장</th>
<th>오차(RSS)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>M0 고정 m</td>
<td>천장은 일정</td>
<td>.007</td>
<td>.156</td>
<td>724만</td>
<td>230</td>
</tr>
<tr class="even">
<td><strong>M1 동적 m</strong></td>
<td><strong>천장 = k × 사찰 수</strong> (공급이 천장을 올림)</td>
<td>.019</td>
<td><strong>.099</strong></td>
<td><strong>k = 5.75만/곳 (±1.75)</strong></td>
<td><strong>114</strong></td>
</tr>
<tr class="odd">
<td>M2 GBM</td>
<td>사찰 수 증가율이 확산 속도를 올림</td>
<td>.006</td>
<td>.129</td>
<td>892만, β = .08</td>
<td>230</td>
</tr>
</tbody>
</table>
<p>(공정한 비교를 위해 같은 형태끼리 비교했습니다: M0 vs M1은 “한 해씩” 형태, 증분 NLS(230) vs M2(230)는 곡선 형태)</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="out/06_fig1_fit.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="6단계 적합"><img src="out/06_fig1_fit.png" class="img-fluid figure-img" alt="6단계 적합"></a></p>
<figcaption>6단계 적합</figcaption>
</figure>
</div>
<p><strong>해석</strong></p>
<ol type="1">
<li><strong>공급은 확산의 “속도”보다 “천장”을 올립니다.</strong> 천장이 사찰 수에 따라 올라가게 한 M1은 오차를 절반(230 → 114)으로 줄였습니다. 반면 속도를 조절하게 한 M2는 효과를 나타내는 β가 0에 가까워 개선이 없었습니다.</li>
<li><strong>입소문 효과(q)가 .156에서 .099로 줄었습니다.</strong> 2단계에서 의심했던 대로, 입소문처럼 보이던 성장의 상당 부분이 사실은 공급 확대의 효과였습니다.</li>
<li><strong>k = 5.75만 명은 “사찰 1곳이 떠받치는 잠재 참가자 규모”</strong>입니다. 2025년 사찰 158곳 기준으로 천장은 약 909만 명이고, 지금까지의 누적 418만 명은 그 46%입니다. 1단계에서 본 “아직 정점 전”이라는 판단과 맞습니다.</li>
<li><strong>예측력은 좋아졌지만 아직 Naive에는 못 미칩니다.</strong> 1년 앞 예측 오차는 고정 m 24.6%, 동적 m 17.4%, Naive 14.0%입니다. 게다가 이 결과는 <strong>다음 해 실제 사찰 수를 미리 안다고 가정한</strong> 조건부 예측입니다.</li>
</ol>
</section>
<section id="정책-시나리오-20262035년-m1-기준" class="level4">
<h4 class="anchored" data-anchor-id="정책-시나리오-20262035년-m1-기준">정책 시나리오 (2026~2035년, M1 기준)</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>시나리오</th>
<th>가정</th>
<th>2035년 사찰</th>
<th>2030년 연간 참가자</th>
<th>2035년 연간 참가자</th>
<th>2035년 누적</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>동결</td>
<td>158곳 유지</td>
<td>158곳</td>
<td>28.8만 (21.6~35.1)</td>
<td>21.9만 (12.1~33.6)</td>
<td>695만</td>
</tr>
<tr class="even">
<td>추세</td>
<td>2015~2025 평균, 매년 +3.6곳</td>
<td>194곳</td>
<td>33.8만 (28.0~38.9)</td>
<td>33.0만 (24.1~42.7)</td>
<td>753만</td>
</tr>
<tr class="odd">
<td>확대</td>
<td>매년 +6곳</td>
<td>218곳</td>
<td>36.9만 (31.8~41.4)</td>
<td>39.7만 (31.5~48.5)</td>
<td>788만</td>
</tr>
</tbody>
</table>
<p>괄호 안은 <strong>80% 부트스트랩 구간</strong>입니다. 모형의 오차를 무작위로 다시 뽑아 가상 자료를 300번 만들고, 매번 다시 추정·예측한 결과의 10~90% 범위입니다. “10번 중 8번은 이 범위 안에 든다” 정도로 읽으면 됩니다.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="out/06_fig2_scenarios.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="6단계 시나리오"><img src="out/06_fig2_scenarios.png" class="img-fluid figure-img" alt="6단계 시나리오"></a></p>
<figcaption>6단계 시나리오</figcaption>
</figure>
</div>
<p><strong>동결 대비 공급 확대 효과</strong></p>
<ul>
<li>추세: 2035년까지 +36곳 → 10년 누적 +57.8만 명, 2035년 연간 +11.1만 명</li>
<li>확대: 2035년까지 +60곳 → 10년 누적 +93.1만 명, 2035년 연간 +17.8만 명 (사찰 1곳당 연 약 3,000명)</li>
</ul>
<blockquote class="blockquote">
<p><strong>“사찰 1곳당 연 약 3,000명”을 읽을 때 주의하세요.</strong> 이 숫자는 <strong>새 사찰 한 곳이 모으는 참가자 수가 아닙니다.</strong> 비교 기준인 “동결” 시나리오는 천장에 다가가며 참가자가 <strong>줄어드는</strong> 경로입니다. 그래서 이 효과에는 “새 참가자” 몫과 함께 <strong>“줄어들 수요를 막은 몫”</strong>이 섞여 있고, 현재 사찰당 평균(2,210명)보다 크게 나옵니다. 보고서에는 “공급을 늘리지 않을 때의 감소를 포함한 차이”로 표현해야 합니다.</p>
</blockquote>
</section>
<section id="민감도-분석-사찰을-늘려도-질이-떨어진다면" class="level4">
<h4 class="anchored" data-anchor-id="민감도-분석-사찰을-늘려도-질이-떨어진다면">민감도 분석: 사찰을 늘려도 질이 떨어진다면?</h4>
<p>M1 모형은 <strong>새 사찰도 기존 사찰과 똑같은 크기의 시장을 연다</strong>고 가정합니다. 현실에서는 그렇지 않을 수 있어서, 이 가정이 깨지는 두 가지 경우를 넣어 봤습니다.</p>
<ul>
<li><strong>α (신규 사찰 효율):</strong> 새 사찰이 기존 사찰의 몇 %만큼 시장을 여는가. α = 0.5면 기존의 절반</li>
<li><strong>q 배수 (입소문 변화):</strong> 새 사찰의 만족도가 낮아 부정적 입소문이 <strong>템플스테이 전체</strong>의 입소문 효과를 약하게 만드는 경우. 새 사찰이 늘어나는 만큼 점차 떨어져 2035년에 해당 배수에 이른다고 가정. q 배수 0.8이면 입소문 효과가 20% 약해짐</li>
</ul>
<p><strong>확대 시나리오의 10년 누적 효과 (동결 대비, 만 명)</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>q 배수 &nbsp;α</th>
<th>1.0</th>
<th>0.75</th>
<th>0.5</th>
<th>0.25</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1.0 (변화 없음)</td>
<td>93.1</td>
<td>71.3</td>
<td>48.6</td>
<td>24.9</td>
</tr>
<tr class="even">
<td>0.9</td>
<td>78.9</td>
<td>58.2</td>
<td>36.7</td>
<td>14.3</td>
</tr>
<tr class="odd">
<td>0.8</td>
<td>64.7</td>
<td>45.1</td>
<td>24.7</td>
<td>3.5</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="out/06_fig3_sensitivity.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="6단계 민감도"><img src="out/06_fig3_sensitivity.png" class="img-fluid figure-img" alt="6단계 민감도"></a></p>
<figcaption>6단계 민감도</figcaption>
</figure>
</div>
<p><strong>해석</strong></p>
<ul>
<li><strong>α가 효과 크기를 거의 비례적으로 좌우합니다.</strong> 새 사찰의 효율이 절반이면 효과도 약 절반입니다.</li>
<li><strong>입소문이 20% 약해지면 효과가 추가로 크게 줄어듭니다.</strong> 효율 절반(α = 0.5)에 입소문 20% 약화가 겹치면 효과는 93.1만에서 24.7만으로 줄어듭니다. <strong>질 관리 실패가 사찰 수 부족보다 더 큰 손실</strong>이 될 수 있습니다.</li>
<li><strong>효과는 시간이 지나야 드러납니다.</strong> 질 관리가 되지 않은 확대 경로는 2030년대 초까지 동결과 거의 비슷하게 움직입니다. 정책을 몇 년 만에 평가하면 효과를 놓칠 수 있습니다.</li>
<li>q가 얼마나, 어떤 속도로 떨어질지는 가정입니다. 이 표는 “이 정도면 이만큼 줄어든다”를 보는 <strong>범위 확인용</strong>입니다.</li>
</ul>
<blockquote class="blockquote">
<p><strong>6단계 요약:</strong> 공급을 천장에 반영하자 모형이 자료에 훨씬 잘 맞았고, “수요는 공급 정책과 그 질에 달려 있다”는 그림이 나왔습니다.</p>
</blockquote>
<hr>
</section>
</section>
</section>
<section id="종합-결론과-교훈" class="level2">
<h2 class="anchored" data-anchor-id="종합-결론과-교훈">6. 종합 결론과 교훈</h2>
<section id="분석-전체를-한-문단으로" class="level3">
<h3 class="anchored" data-anchor-id="분석-전체를-한-문단으로">6.1 분석 전체를 한 문단으로</h3>
<p>공급 확대와 재참가로 계속 성장하는 자료에 기본 Bass 모형을 적용하면, 모형은 <strong>작은 둔화가 올 때마다 포화로 읽어서 천장을 낮게, 정점을 이르게</strong> 추정합니다. 새 자료가 들어오면 천장과 정점을 뒤로 미루는 일을 반복합니다. 공급을 천장에 반영하면 “수요는 이미 포화 중”이 아니라 <strong>“수요는 공급 정책과 그 질에 달려 있다”</strong>는 전혀 다른 그림이 나옵니다.</p>
</section>
<section id="기본-bass-모형의-가정과-템플스테이의-현실" class="level3">
<h3 class="anchored" data-anchor-id="기본-bass-모형의-가정과-템플스테이의-현실">6.2 기본 Bass 모형의 가정과 템플스테이의 현실</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>모형의 가정</th>
<th>템플스테이 자료</th>
<th>결과에 미친 영향</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>한 사람은 한 번만 채택</td>
<td>재참가가 있음 (순인원도 해마다 새로 셈)</td>
<td>포화가 늦게 오고, 천장의 의미가 모호해짐</td>
</tr>
<tr class="even">
<td>천장 m은 고정</td>
<td>사찰 수·프로그램이 늘며 시장이 커짐</td>
<td>천장 과소추정, 너무 이른 포화 판단</td>
</tr>
<tr class="odd">
<td>공급 제약 없음</td>
<td>사찰 수용 능력이 참가자를 제한</td>
<td>공급 정체기를 포화로 착각, 입소문 효과 과대추정</td>
</tr>
<tr class="even">
<td>p·q는 일정</td>
<td>코로나, 외국인 유입, 정책 변화</td>
<td>추정 불안정</td>
</tr>
</tbody>
</table>
</section>
<section id="이-실습에서-얻는-교훈" class="level3">
<h3 class="anchored" data-anchor-id="이-실습에서-얻는-교훈">6.3 이 실습에서 얻는 교훈</h3>
<ol type="1">
<li><strong>자료의 정의부터 확인하세요.</strong> “무엇을 셌는가(순인원/연인원)”를 확인한 것만으로 논문과 숫자가 다른 이유가 풀렸습니다.</li>
<li><strong>계산 방법을 하나만 쓰지 마세요.</strong> 방법에 따라 천장이 300만~400만 명씩 달라졌습니다.</li>
<li><strong>이미 있는 자료를 잘 설명하는 것과 미래를 맞히는 것은 다릅니다.</strong> 반드시 처음 보는 기간으로 시험하고, 단순 예측(Naive, Drift)과 비교하세요.</li>
<li><strong>모형이 매번 같은 방향으로 틀리면 가정을 의심하세요.</strong> “곧 포화”를 반복하다 밀려나는 패턴은 천장이 고정되어 있다는 가정이 틀렸다는 신호였습니다.</li>
<li><strong>모든 모형은 틀립니다. 다만 일부는 유용합니다</strong>(George Box). 물어야 할 것은 “이 모형이 맞는가”보다 <strong>“이 모형의 가정이 내 자료와 얼마나 다르고, 그 차이가 결론을 어느 방향으로 비트는가”</strong>입니다. 방향을 알면 결과를 보정해서 읽을 수 있습니다. 예를 들어 “천장은 최소한 이 정도 이상일 것”처럼요.</li>
</ol>
<hr>
</section>
</section>
<section id="정책에-주는-시사점" class="level2">
<h2 class="anchored" data-anchor-id="정책에-주는-시사점">7. 정책에 주는 시사점</h2>
<ol type="1">
<li><strong>“수요가 언제 포화되는가”보다 “공급을 늘리면 수요가 얼마나 생기는가”가 핵심 질문입니다.</strong> 동적 m 모형은 이 질문에 숫자로 답할 수 있는 출발점을 줍니다.</li>
<li><strong>공급의 양만큼 질이 중요합니다.</strong> 새 사찰의 효율(α)과 입소문 효과(q)를 지켜볼 지표가 필요합니다.
<ul>
<li>α를 가늠하는 지표: 신규 사찰의 사찰당 참가자 수</li>
<li>q를 가늠하는 지표: 만족도 조사의 추천 의향, 재참가 의향</li>
</ul></li>
<li><strong>인과는 따로 검증해야 합니다.</strong> 이번 분석은 사찰 수와 수요가 <strong>함께 움직였다</strong>는 것을 모형으로 표현한 것이지, 사찰을 늘리면 수요가 늘어난다는 것을 <strong>증명</strong>한 것은 아닙니다. 사업 효과를 엄밀히 평가하려면 사찰별·지역별 자료로 신규 운영 전후를 비교하는 <strong>이중차분법(DID)</strong> 같은 설계가 필요합니다.</li>
<li><strong>조사 자료로 모형의 약점을 보완할 수 있습니다.</strong> 참가자 만족도 조사에 “재참가 여부” 문항이 있다면, <strong>연간 순인원 × (1 − 재참가 비율)</strong>로 처음 참가한 사람 수를 근사할 수 있습니다. 그러면 “한 사람은 한 번만”이라는 모형의 가정에 더 가까운 자료가 됩니다.</li>
</ol>
<hr>
</section>
<section id="내-자료에-적용할-때-체크리스트와-함정" class="level2">
<h2 class="anchored" data-anchor-id="내-자료에-적용할-때-체크리스트와-함정">8. 내 자료에 적용할 때: 체크리스트와 함정</h2>
<section id="단계별-체크리스트" class="level3">
<h3 class="anchored" data-anchor-id="단계별-체크리스트">8.1 단계별 체크리스트</h3>
<p><strong>① 분석 전: 자료 점검</strong></p>
<ul class="task-list">
<li><label><input type="checkbox"><strong>무엇을 셌는가?</strong> 사람 수인가, 건수·연인원인가? 모형의 “채택자” 개념과 맞는가?</label></li>
<li><label><input type="checkbox"><strong>재구매·재방문이 섞여 있는가?</strong> 섞여 있다면 m은 “채택자 규모”가 아니라 “포화 전까지 쌓일 규모”로 해석한다.</label></li>
<li><label><input type="checkbox"><strong>출처가 여러 개라면 겹치는 기간으로 교차 검증했는가?</strong> 합계·누적이 맞는지, 내역의 합이 합계와 같은지 확인한다.</label></li>
<li><label><input type="checkbox"><strong>도입 초기부터 관측됐는가?</strong> 앞부분이 잘렸다면 도입 시점과 관측 직전 누적값을 확보한다.</label></li>
<li><label><input type="checkbox"><strong>이상 연도</strong>(특수 이벤트, 외부 충격)를 표시해 두었는가?</label></li>
<li><label><input type="checkbox"><strong>공급·가격·정책 변수</strong>를 함께 확보했는가? (매장 수, 요금, 예산 등)</label></li>
</ul>
<p><strong>② 모형 전에 그림부터</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">연간값과 누적값 그래프: 연간값이 정점을 지났는가? 감소가 <strong>계속되는가</strong>?</label></li>
<li><label><input type="checkbox"><strong>위상도:</strong> 뒤집힌 U자가 보이는가? 오른쪽 끝(천장)을 자료가 직접 보여 주는가?</label></li>
<li><label><input type="checkbox">공급 변수와 수요를 겹쳐 그려 보고, “공급 × 공급 단위당 수요”로 나눠 본다.</label></li>
</ul>
<p><strong>③ 추정: 최소 세 가지 방법을 나란히</strong></p>
<ul class="task-list">
<li><label><input type="checkbox"><strong>OLS, 누적 NLS, 증분 NLS</strong>를 모두 돌려 천장과 정점이 얼마나 갈리는지 본다.</label></li>
<li><label><input type="checkbox"><strong>표준오차</strong>를 확인한다. m의 표준오차가 추정값의 절반을 넘으면 “천장은 정해지지 않았다”고 보고한다.</label></li>
<li><label><input type="checkbox">누적 NLS의 작은 표준오차는 그대로 믿지 않는다.</label></li>
<li><label><input type="checkbox">NLS는 <strong>여러 시작값</strong>으로 돌린다.</label></li>
<li><label><input type="checkbox"><strong>잔차 그림</strong>에서 오차가 한쪽으로 몰리는지 확인한다.</label></li>
</ul>
<p><strong>④ 설정 바꿔 보기</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">출발 연도, 외부 충격 처리(포함/제외/더미)를 바꿔도 결론이 유지되는지 확인한다.</label></li>
<li><label><input type="checkbox">방법 간 차이와 설정 간 차이 중 어느 쪽이 더 큰지 본다.</label></li>
</ul>
<p><strong>⑤ 검증: 반드시 처음 보는 기간으로</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">최근 몇 년을 숨기고 맞히는지 본다 (holdout).</label></li>
<li><label><input type="checkbox">예측 시작 시점을 옮겨 가며 반복한다 (rolling origin).</label></li>
<li><label><input type="checkbox"><strong>Naive, Drift와 비교</strong>한다. 이기지 못하면 “점 예측 도구로는 부적합”이라고 보고한다.</label></li>
<li><label><input type="checkbox">예측치가 <strong>실제값에서 한 해씩 예측한 것</strong>인지, <strong>0에서 출발한 가상 경로</strong>인지 구분해 보고한다.</label></li>
</ul>
<p><strong>⑥ 확장과 시나리오</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">공급·마케팅 변수가 있다면 <strong>동적 m</strong>과 <strong>GBM</strong>을 모두 시험해, 공급이 “천장”을 올리는지 “속도”를 올리는지 본다.</label></li>
<li><label><input type="checkbox">정책 시나리오는 <strong>동결(기준) 대비 차이</strong>로 제시하고, 그 차이에 “감소 방지 몫”이 섞였는지 설명한다.</label></li>
<li><label><input type="checkbox">핵심 가정(공급 단위 효율, 입소문 효과)에 <strong>민감도 분석</strong>을 붙인다.</label></li>
<li><label><input type="checkbox">불확실성 구간(부트스트랩 등)을 함께 제시한다.</label></li>
</ul>
</section>
<section id="자주-빠지는-해석의-함정" class="level3">
<h3 class="anchored" data-anchor-id="자주-빠지는-해석의-함정">8.2 자주 빠지는 해석의 함정</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>함정</th>
<th>왜 문제인가</th>
<th>이번 사례</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>“누적이 계속 늘어나니 아직 성장 중”</td>
<td>누적은 원래 줄지 않는다. 정점은 <strong>연간값</strong>으로 판단해야 한다</td>
<td>1단계</td>
</tr>
<tr class="even">
<td>“한 해 줄었으니 정점을 지났다”</td>
<td>일시적 감소일 수 있다. 감소가 <strong>계속되는지</strong> 봐야 한다</td>
<td>2012년, 2020년</td>
</tr>
<tr class="odd">
<td>“R²가 높으니 예측도 잘할 것”</td>
<td>이미 있는 자료를 잘 설명하는 것과 미래를 맞히는 것은 다르다</td>
<td>Bass가 Naive에 짐</td>
</tr>
<tr class="even">
<td>“q가 크니 입소문 효과가 강하다”</td>
<td>공급 확대 효과를 q가 떠안았을 수 있다</td>
<td>q .156 → .099</td>
</tr>
<tr class="odd">
<td>“표준오차가 작으니 정확하다”</td>
<td>누적값에 맞추면 표준오차가 실제보다 작게 나온다</td>
<td>누적 NLS</td>
</tr>
<tr class="even">
<td>“모든 연도에서 과대추정 = 모형이 편향됨”</td>
<td>0에서 출발한 가상 경로라서 초기 오차가 쌓인 것일 수 있다</td>
<td>논문 표 1</td>
</tr>
<tr class="odd">
<td>“사찰 1곳 추가 = 연 3,000명 추가”</td>
<td>기준 시나리오의 감소 방지 몫이 섞여 있다</td>
<td>6단계</td>
</tr>
<tr class="even">
<td>“공급과 수요가 같이 움직였으니 공급이 수요를 만든다”</td>
<td>반대 방향일 수도 있다. 관측 자료만으로 인과를 단정할 수 없다</td>
<td>전 과정</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="결과를-보고하는-법" class="level2">
<h2 class="anchored" data-anchor-id="결과를-보고하는-법">9. 결과를 보고하는 법</h2>
<section id="표현-원칙" class="level3">
<h3 class="anchored" data-anchor-id="표현-원칙">9.1 표현 원칙</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>피해야 할 표현</th>
<th>권장 표현</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>잠재시장은 734만 명이다</td>
<td>추정 방법에 따라 잠재시장은 524만~858만 명으로 추정되어, 규모를 특정하기 어렵다</td>
</tr>
<tr class="even">
<td>2020년이 수요의 정점이다</td>
<td>기본 Bass 모형은 2018~2024년을 정점으로 추정했으나, 실제 연간 참가자는 2025년이 최대였다</td>
</tr>
<tr class="odd">
<td>모형의 설명력이 높아 예측이 신뢰할 만하다</td>
<td>표본 밖 검증에서 모형의 예측 오차는 ○○%로, 단순 예측(Naive ○○%)보다 컸다</td>
</tr>
<tr class="even">
<td>사찰을 늘리면 수요가 늘어난다</td>
<td>사찰 수와 수요는 함께 움직였으며, 사찰 수를 반영한 모형에서 공급 확대 시나리오의 수요가 더 높게 나타났다 (인과는 별도 검증 필요)</td>
</tr>
<tr class="odd">
<td>사찰 1곳당 연 3,000명이 늘어난다</td>
<td>동결 대비 확대 시나리오의 차이는 사찰 1곳당 연 약 3,000명이며, 여기에는 동결 시의 수요 감소를 막은 몫이 포함된다</td>
</tr>
</tbody>
</table>
</section>
<section id="보고서에-담을-내용" class="level3">
<h3 class="anchored" data-anchor-id="보고서에-담을-내용">9.2 보고서에 담을 내용</h3>
<ol type="1">
<li>자료의 정의(순인원/연인원 등)와 출처, 정정 사항</li>
<li>추정 방법과 예측치 계산 방식 (한 해씩 예측인지, 가상 경로인지)</li>
<li>표준오차 또는 불확실성 구간</li>
<li>표본 밖 검증 결과와 벤치마크 비교</li>
<li>모형 가정과 자료의 차이, 그 차이가 결론을 어느 방향으로 비트는지</li>
<li>인과를 증명하지 않았다는 점</li>
</ol>
<hr>
</section>
</section>
<section id="파일-구성과-실행-방법" class="level2">
<h2 class="anchored" data-anchor-id="파일-구성과-실행-방법">10. 파일 구성과 실행 방법</h2>
<section id="폴더-구성" class="level3">
<h3 class="anchored" data-anchor-id="폴더-구성">10.1 폴더 구성</h3>
<pre><code>BassModel/
├─ templestay_2002to2025.csv        # 통합 자료 (순인원 2002~2025, 연인원 2002~2021, 사찰 수)
├─ bass_functions.R                 # 공용 함수 (각 스크립트가 불러 씀. 따로 실행할 필요 없음)
├─ 01_data_explore.R                # 1단계: 자료 살펴보기
├─ 02_bass_fit.R                    # 2단계: 세 가지 추정법
├─ 03_specification.R               # 3단계: 설정 비교
├─ 04_forecast_validate.R           # 4단계: 예측 시험, 논문 재현
├─ 05_rolling_origin.R              # 5단계: rolling origin
├─ 06_supply_scenarios.R            # 6단계: 공급 반영 모형, 시나리오, 민감도
├─ Bass확산모형_분석가이드_템플스테이.md   # 이 문서
└─ out/                             # 모든 그래프(PNG)와 결과표(CSV)</code></pre>
</section>
<section id="실행-방법" class="level3">
<h3 class="anchored" data-anchor-id="실행-방법">10.2 실행 방법</h3>
<ol type="1">
<li><p>R(4.2 이상 권장)을 열고 작업 폴더를 지정합니다.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"내려받은/폴더/경로/bass-diffusion"</span>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div></li>
<li><p>단계별 스크립트를 순서대로 실행합니다. <strong>추가 패키지가 필요 없습니다</strong>(base R만 사용).</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"01_data_explore.R"</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"02_bass_fit.R"</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ... 06까지</span></span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div></li>
<li><p>결과는 콘솔에 표로 나오고, 그래프와 CSV는 <code>out/</code> 폴더에 저장됩니다.</p></li>
</ol>
</section>
<section id="다른-자료에-적용하려면" class="level3">
<h3 class="anchored" data-anchor-id="다른-자료에-적용하려면">10.3 다른 자료에 적용하려면</h3>
<ul>
<li><code>bass_functions.R</code>의 <code>load_templestay()</code>를 참고해, <strong>연도(year), 연간값, 공급 변수</strong>가 있는 CSV를 읽는 함수를 만듭니다. 모형은 연간값을 <code>n</code>, 누적을 <code>N</code>, 도입 후 연차를 <code>t</code> 열로 사용합니다.</li>
<li>단위를 맞춰 주세요(이번 분석은 만 명). 숫자가 너무 크거나 작으면 NLS 계산이 수렴하지 않을 수 있습니다.</li>
<li>공급 변수가 있다면 <code>06_supply_scenarios.R</code>의 <code>S</code> 열(사찰 수) 자리에 넣으면 됩니다.</li>
</ul>
</section>
<section id="주요-함수-bass_functions.r" class="level3">
<h3 class="anchored" data-anchor-id="주요-함수-bass_functions.r">10.4 주요 함수 (<code>bass_functions.R</code>)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>함수</th>
<th>역할</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>bass_F(t, p, q)</code></td>
<td>누적 채택 비율 F(t)</td>
</tr>
<tr class="even">
<td><code>bass_N(t, p, q, m)</code> / <code>bass_n(t, p, q, m)</code></td>
<td>누적 / 연간 채택자</td>
</tr>
<tr class="odd">
<td><code>bass_peak(p, q, m)</code></td>
<td>정점 시점·규모·누적 비율</td>
</tr>
<tr class="even">
<td><code>fit_ols(d)</code></td>
<td>OLS 추정 (<code>covid_dummy = TRUE</code>로 더미 추가 가능)</td>
</tr>
<tr class="odd">
<td><code>fit_nls_cum(d)</code> / <code>fit_nls_inc(d)</code></td>
<td>누적 NLS / 증분 NLS (다중 시작점)</td>
</tr>
<tr class="even">
<td><code>fit_nls_inc_dummy(d)</code></td>
<td>증분 NLS + 코로나 더미</td>
</tr>
<tr class="odd">
<td><code>summarise_fit(r, d, t0)</code></td>
<td>추정 결과 요약 (정점, 도달률, RMSE, R²)</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="자주-묻는-질문" class="level2">
<h2 class="anchored" data-anchor-id="자주-묻는-질문">11. 자주 묻는 질문</h2>
<p><strong>Q1. p와 q는 각각 어느 정도면 큰 건가요?</strong> 여러 제품의 평균은 대략 p ≈ 0.03, q ≈ 0.38입니다. 보통 q가 p보다 훨씬 커서, q/p가 클수록 입소문 중심의 S자 확산입니다. 다만 이번 사례처럼 공급 확대 같은 다른 요인이 q에 섞여 들어갈 수 있으니, 숫자 자체보다 <strong>무엇이 섞였을지</strong>를 먼저 생각하세요.</p>
<p><strong>Q2. 왜 계산 방법마다 천장(m)이 이렇게 다른가요?</strong> 정점을 지나지 않은 자료에서는 곡선의 오른쪽 끝(천장)을 자료가 직접 보여 주지 않습니다. 천장은 곡선이 휘어지는 정도로부터 <strong>추측</strong>해야 하는데, 방법마다 그 휘어짐을 다르게 읽기 때문입니다. 방법마다 결과가 크게 다르다면 그 자체가 “천장을 알 수 없다”는 정보입니다.</p>
<p><strong>Q3. 단순 예측(Naive)에 졌는데 Bass 모형을 왜 쓰나요?</strong> 점 예측(내년에 정확히 몇 명)에는 약할 수 있지만, 확산 구조를 해석하거나(광고 vs 입소문), 시나리오를 비교하거나, 자료가 없는 신제품을 예측하는 데는 여전히 유용합니다 (3.4 참고). 다만 <strong>점 예측 용도로 쓰려면 반드시 벤치마크를 이겨야 합니다.</strong></p>
<p><strong>Q4. 재구매·재참가가 섞인 자료는 아예 쓸 수 없나요?</strong> 쓸 수는 있지만 해석을 바꿔야 합니다. m은 “채택할 사람 수”가 아니라 “포화 전까지 쌓일 규모”가 됩니다. 조사 자료로 재참가 비율을 알 수 있다면 처음 참가자만 근사해서 쓰는 방법도 있습니다 (7장 4번).</p>
<p><strong>Q5. 코로나 같은 충격 기간은 어떻게 처리하나요?</strong> ① 포함, ② 제외, ③ 더미 변수 세 가지를 모두 돌려 결론이 같은지 보세요. 이번 사례에서는 제외와 더미가 거의 같은 결과를 줬고, 포함하면 추정이 불안정해졌습니다.</p>
<p><strong>Q6. 부트스트랩 구간은 어떻게 읽나요?</strong> “모형 추정이 이만큼 흔들린다면 예측은 이 범위에서 움직인다”는 뜻입니다. 80% 구간은 “10번 중 8번은 이 범위”로 읽으면 됩니다. 다만 모형의 가정 자체가 틀렸을 때의 불확실성까지 담지는 못합니다.</p>
<p><strong>Q7. 정책 효과를 정확히 알려면 무엇이 더 필요한가요?</strong> 이번 분석은 “함께 움직였다”를 모형화한 것입니다. “사찰을 늘렸기 때문에 늘었다”를 확인하려면, 사찰별·지역별 자료로 신규 사찰이 생긴 곳과 그렇지 않은 곳의 전후 변화를 비교하는 <strong>이중차분법(DID)</strong> 같은 방법이 필요합니다.</p>
<hr>
</section>
<section id="참고문헌" class="level2">
<h2 class="anchored" data-anchor-id="참고문헌">12. 참고문헌</h2>
<ul>
<li>강문영 (2024). Bass 확산 모형을 기반으로 한 템플스테이 수요 예측. <em>상품학연구</em>, 42(5), 35–39.</li>
<li>한국불교문화사업단 (2022). 『템플스테이 20년사』.</li>
<li>연합뉴스 (2026). 템플스테이 참가자 현황 표 (한국불교문화사업단 제공), 기사 AKR20260115161800005.</li>
<li>Bass, F. M. (1969). A new product growth for model consumer durables. <em>Management Science</em>, 15(5), 215–227.</li>
<li>Bass, F. M., Krishnan, T. V., &amp; Jain, D. C. (1994). Why the Bass model fits without decision variables. <em>Marketing Science</em>, 13(3), 203–223.</li>
<li>Heeler, R. M., &amp; Hustad, T. P. (1980). Problems in predicting new product growth for consumer durables. <em>Management Science</em>, 26(10), 1007–1020.</li>
<li>Lenk, P. J., &amp; Rao, A. G. (1990). New models from old: Forecasting product adoption by hierarchical Bayes procedures. <em>Marketing Science</em>, 9(1), 42–53.</li>
<li>Lilien, G. L., Rao, A. G., &amp; Kalish, S. (1981). Bayesian estimation and control of detailing effort in a repeat purchase diffusion environment. <em>Management Science</em>, 27(5), 493–506.</li>
<li>Mahajan, V., &amp; Peterson, R. A. (1978). Innovation diffusion in a dynamic potential adopter population. <em>Management Science</em>, 24(15), 1589–1597.</li>
<li>Rogers, E. M. (1962). <em>Diffusion of Innovations</em>. New York: Free Press.</li>
<li>Srinivasan, V., &amp; Mason, C. H. (1986). Nonlinear least squares estimation of new product diffusion models. <em>Marketing Science</em>, 5(2), 169–178.</li>
<li>Sultan, F., Farley, J. U., &amp; Lehmann, D. R. (1990). A meta-analysis of applications of diffusion models. <em>Journal of Marketing Research</em>, 27(1), 70–77.</li>
</ul>
<hr>
<p><em>작성: 2026년 9월 · 분석 도구: R (base R) · 문의 및 수정 제안은 정진우(jinwoo.chung@kstat.co.kr)에게 해주세요.</em></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "복사완료!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "복사완료!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/jinwoochung\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2026 정진우 · 공개 데이터로 만든 실습 자료입니다. 자유롭게 참고하되 출처를 밝혀 주세요.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>